### ISSUE TITLE
Failed to create tenant (inconsistent)

### ISSUE THREAD

**Issue by yientau** [hyn/multi-tenant#108]
Sometimes it creates tenant successfully but there are some other times it fails to create. The following are the error trace.

[error.txt](https://github.com/hyn/multi-tenant/files/355910/error.txt)

I am running this on latest XAMPP(PHP 7.0.8, Apache 2.4.18, MariaDB 10.1.13) on my local machine(using Mac). It actually also happens when I was using PHP5.

**Comment by luceos** [comment]
```
[2016-07-07 02:18:03] local.ERROR: exception 'InvalidArgumentException' with message 'View [webserver.apache.configuration] not found.' in /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(92): Illuminate\View\FileViewFinder->findInPaths('webserver.apach...', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamedPathView('webserver::webs...')
#2 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/View/Factory.php(165): Illuminate\View\FileViewFinder->find('webserver::webs...')
#3 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(779): Illuminate\View\Factory->make('webserver::webs...', Array, Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/hyn/multi-tenant/src/Webserver/Generators/Webserver/Apache.php(23): view('webserver::webs...', Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/hyn/multi-tenant/src/Webserver/Generators/AbstractFileGenerator.php(39): Hyn\Webserver\Generators\Webserver\Apache->generate()
#6 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/hyn/multi-tenant/src/Webserver/Generators/AbstractFileGenerator.php(61): Hyn\Webserver\Generators\AbstractFileGenerator->onCreate()
#7 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/hyn/multi-tenant/src/Webserver/Commands/WebserverCommand.php(58): Hyn\Webserver\Generators\AbstractFileGenerator->onUpdate()
#8 [internal function]: Hyn\Webserver\Commands\WebserverCommand->handle()
#9 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(82): Illuminate\Container\Container->call(Array)
#11 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Hyn\Webserver\Commands\WebserverCommand))
#12 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(150): call_user_func(Object(Closure), Object(Hyn\Webserver\Commands\WebserverCommand))
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Hyn\Webserver\Commands\WebserverCommand))
#14 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Hyn\Webserver\Commands\WebserverCommand))
#15 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(83): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(41): Illuminate\Bus\Dispatcher->dispatchNow(Object(Hyn\Webserver\Commands\WebserverCommand))
#17 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(130): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#18 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Queue/Jobs/SyncJob.php(44): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#19 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(30): Illuminate\Queue\Jobs\SyncJob->fire()
#20 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(143): Illuminate\Queue\SyncQueue->push(Object(Hyn\Webserver\Commands\WebserverCommand))
#21 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(118): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\SyncQueue), Object(Hyn\Webserver\Commands\WebserverCommand))
#22 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(67): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(Hyn\Webserver\Commands\WebserverCommand))
#23 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Hyn\Webserver\Commands\WebserverCommand))
#24 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/hyn/multi-tenant/src/Webserver/Observers/WebsiteObserver.php(23): Hyn\Webserver\Observers\WebsiteObserver->dispatch(Object(Hyn\Webserver\Commands\WebserverCommand))
#25 [internal function]: Hyn\Webserver\Observers\WebsiteObserver->updated(Object(Hyn\MultiTenant\Models\Website))
#26 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(348): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Hyn\MultiTenant\Models\Website))
#28 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#29 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1686): Illuminate\Events\Dispatcher->fire('eloquent.update...', Object(Hyn\MultiTenant\Models\Website))
#30 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1564): Illuminate\Database\Eloquent\Model->fireModelEvent('updated', false)
#31 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1481): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#32 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/hyn/multi-tenant/src/Framework/Models/AbstractModel.php(96): Illuminate\Database\Eloquent\Model->save(Array)
#33 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1729): Hyn\Framework\Models\AbstractModel->save()
#34 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/hyn/multi-tenant/src/Tenancy/Observers/HostnameObserver.php(16): Illuminate\Database\Eloquent\Model->touch()
#35 [internal function]: Hyn\MultiTenant\Observers\HostnameObserver->saved(Object(Hyn\MultiTenant\Models\Hostname))
#36 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(348): call_user_func_array(Array, Array)
#37 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Hyn\MultiTenant\Models\Hostname))
#38 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#39 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1686): Illuminate\Events\Dispatcher->fire('eloquent.saved:...', Object(Hyn\MultiTenant\Models\Hostname))
#40 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1521): Illuminate\Database\Eloquent\Model->fireModelEvent('saved', false)
#41 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1492): Illuminate\Database\Eloquent\Model->finishSave(Array)
#42 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/hyn/multi-tenant/src/Framework/Models/AbstractModel.php(96): Illuminate\Database\Eloquent\Model->save(Array)
#43 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/hyn/multi-tenant/src/Framework/Repositories/BaseRepository.php(47): Hyn\Framework\Models\AbstractModel->save()
#44 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/app/Http/Controllers/Signup/SignupController.php(85): Hyn\Framework\Repositories\BaseRepository->create(Array)
#45 [internal function]: App\Http\Controllers\Signup\SignupController->store(Object(Illuminate\Http\Request))
#46 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#47 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('store', Array)
#48 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Signup\SignupController), Object(Illuminate\Routing\Route), 'store')
#49 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Signup\SignupController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'store')
#55 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'store')
#56 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#57 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#63 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#64 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#65 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#67 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#71 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#76 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#81 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#82 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#83 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#84 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#86 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#88 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#89 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#90 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#91 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#92 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#93 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#94 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#95 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#96 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#97 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#98 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/hyn/multi-tenant/src/Tenancy/Middleware/HostnameMiddleware.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#99 [internal function]: Hyn\MultiTenant\Middleware\HostnameMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#100 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#101 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#102 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#103 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#104 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#105 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#106 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#107 /Applications/XAMPP/xamppfiles/htdocs/staffmanagementapp/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#108 {main}  
```

**Comment by luceos** [comment]
https://github.com/hyn/multi-tenant/tree/multi-tenant-108

Started work on sorting this out properly. This is a preliminary fix, I need to test it still.
