### ISSUE TITLE
HostnameValidator uses wrong connection when using Associate

### ISSUE THREAD

**Issue by BertKooij** [hyn/multi-tenant#223]
__Description__

After creating a new customer and website successfully, the creation of a new hostname fails when I associate the website and customer instead of using the website_id and customer_id. The issues seems to be limited to the HostnameValidator. When I comment this line out: https://github.com/hyn/multi-tenant/blob/3.x/src/Repositories/HostnameRepository.php#L93 the hostname will be created without any errors.

```php
$hostname = new Hostname();
$hostname->fqdn = $this->ask('What is the hostname?');
$hostname->website()->associate($website); // Instance of Website
$hostname->customer()->associate($customer); // Instance of Customer
if($this->hostnameRepository->create($hostname)) {
     $this->info('Hostname created: (ID: ' . $hostname->id . ')');
}
```

For now using `$hostname->website_id = $website->id` is working fine. 

---

__Actual behavior__

The HostnameValidator uses the `tenant-migration` connection.

__Expected behavior__

The HostnameValidator must use the `system` connection.

---
__Information__

- hyn/multi-tenant version: 3.x-dev
- laravel version: 5.4.28
- database driver and version: MySQL 5.7
- php version: 7.1

---

__Error log__

```text
Undefined index: driver
ErrorException: Undefined index: driver in /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:113
Stack trace:
#0 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(113): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/home/vagrant/d...', 113, Array)
#1 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(72): Illuminate\Database\DatabaseManager->makeConnection('tenant-migratio...')
#2 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Validation/DatabasePresenceVerifier.php(125): Illuminate\Database\DatabaseManager->connection('tenant-migratio...')
#3 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Validation/DatabasePresenceVerifier.php(49): Illuminate\Validation\DatabasePresenceVerifier->table('websites')
#4 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php(579): Illuminate\Validation\DatabasePresenceVerifier->getCount('websites', 'id', 100, NULL, NULL, Array)
#5 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php(550): Illuminate\Validation\Validator->getExistCount(NULL, 'websites', 'id', 100, Array)
#6 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(352): Illuminate\Validation\Validator->validateExists('website_id', 100, Array, Object(Illuminate\Validation\Validator))
#7 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(267): Illuminate\Validation\Validator->validateAttribute('website_id', 'Exists')
#8 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(292): Illuminate\Validation\Validator->passes()
#9 /home/vagrant/app/vendor/hyn/multi-tenant/src/Abstracts/Validator.php(103): Illuminate\Validation\Validator->fails()
#10 /home/vagrant/app/vendor/hyn/multi-tenant/src/Abstracts/Validator.php(82): Hyn\Tenancy\Abstracts\Validator->validate(Object(Hyn\Tenancy\Models\Hostname), Array)
#11 /home/vagrant/app/vendor/hyn/multi-tenant/src/Abstracts/Validator.php(47): Hyn\Tenancy\Abstracts\Validator->create(Object(Hyn\Tenancy\Models\Hostname))
#12 /home/vagrant/app/vendor/hyn/multi-tenant/src/Repositories/HostnameRepository.php(93): Hyn\Tenancy\Abstracts\Validator->save(Object(Hyn\Tenancy\Models\Hostname))
#13 /home/vagrant/app/app/Console/Commands/NewTenantCommand.php(106): Hyn\Tenancy\Repositories\HostnameRepository->create(Object(Hyn\Tenancy\Models\Hostname))
#14 [internal function]: App\Console\Commands\NewTenantCommand->handle()
#15 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#16 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#18 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#19 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#20 /home/vagrant/app/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#21 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#22 /home/vagrant/app/vendor/symfony/console/Application.php(869): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/vagrant/app/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\NewTenantCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output
\ConsoleOutput))
#24 /home/vagrant/app/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/vagrant/app/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 {main}
```

**Comment by luceos** [comment]
@beko1997 working on a fix ;) Thanks for your extensive report, much appreciated.
