### ISSUE TITLE
Redis loose tenant when dispatching job.

### ISSUE THREAD

**Issue by hpiMat** [hyn/multi-tenant#246]
__Description__

...
Hello,
 I'm using laravel 5.4 with hyn multi tenancy. Everything is working as intended exept when interacting with redis (1.1.1).  Before dispatching a job on a queue, the tenant is well configured as an environment and interact well with models. As soon as i dispatch a job with the following configuration:
`use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;`

---

__Actual behavior__

..
At some point, the tenant is lost and the job will automatically fail.
I even tried in the job constructor and handle function, to get back the environment and setback the tenancy hostname but the error is precisely located before all of this happens.
It was working with redis before i implemented multi-tenancy. Wonderful work on this package!
Matthieu

__Expected behavior__

..
I don't know where in the configuration i should tell Hyn to connect to a specific tenant for redis to work.

---
__Information__

- hyn/multi-tenant version:1.1.1
- laravel version:5.4
- database driver and version:
- webserver software and version:apache2
- php version:7.1

---

__tenancy.php config__

```php
'website' => [
        /**
         * Each website has a short random hash that identifies this entity
         * to the application. By default this id is randomized and fully
         * auto-generated. In case you want to force your own logic fi
         * when you need to have a better overview of the complete
         * tenant folder structure, disable this and implement
         * your own id generation logic.
         *
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-websitedisable-random-id
         */
        'disable-random-id' => false,

        /**
         * The random Id generator is responsible for creating the hash as mentioned
         * above. You can override what generator to use by modifying this value
         * in the configuration.
         *
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-websiterandom-id-generator
         * @warn This won't work if disable-random-id is true.
         */
        'random-id-generator' => App\RandomIdGenerator::class,

        /**
         * Specify the disk you configured in the filesystems.php file where to store
         * the tenant specific files, including media, packages, routes and other
         * files for this particular website.
         *
         * @see
         * @info If not set, will revert to the default filesystem.
         */
        'disk' => null,

        /**
         * Automatically generate a tenant directory based on the random id of the
         * website. Uses the above disk to store files to override system-wide
         * files.
         *
         * @see
         * @info set to false to disable.
         */
        'auto-create-tenant-directory' => false,

        /**
         * Automatically rename the tenant directory when the random id of the
         * website changes. This should not be too common, but in case it happens
         * we automatically want to move files accordingly.
         *
         * @see
         * @info set to false to disable.
         */
        'auto-rename-tenant-directory' => false,

        /**
         * Automatically deletes the tenant specific directory and all files
         * contained within.
         *
         * @see
         * @info set to true to enable.
         */
        'auto-delete-tenant-directory' => false,

        /**
         * Time to cache websites in minutes. Set to false to disable.
         */
        'cache' => 10,
    ],
    'hostname' => [
        /**
         * If you want the multi tenant application to fall back to a default
         * hostname/website in case the requested hostname was not found
         * in the database, complete in detail the default hostname.
         *
         * @warn this must be a FQDN, these have no protocol or path!
         *
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-hostnamedefault
         */
        'default' => env('TENANCY_DEFAULT_HOSTNAME'),
        /**
         * The package is able to identify the requested hostname by itself,
         * disable to get full control (and responsibility) over hostname
         * identification. The hostname identification is needed to
         * set a specific website as currently active.
         *
         * @see src/Jobs/HostnameIdentification.php
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-hostnameauto-identification
         */
        'auto-identification' => env('TENANCY_AUTO_HOSTNAME_IDENTIFICATION', true),
        /**
         * Abort application execution in case no hostname was identified. This will throw a
         * 404 not found in case the tenant hostname was not resolved.
         *
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-hostnameabort-without-identified-hostname
         */
        'abort-without-identified-hostname' => true,

        /**
         * Time to cache hostnames in minutes. Set to false to disable.
         */
        'cache' => 10,
    ],
    'db' => [
        /**
         * The default connection to use; this overrules the Laravel database.default
         * configuration setting. In Laravel this is normally configured to 'mysql'.
         * You can set a environment variable to override the default database
         * connection to - for instance - the tenant connection 'tenant'.
         *
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-dbdefault
         */
        'default' => env('TENANCY_DEFAULT_CONNECTION'),
        /**
         * Used to give names to the system and tenant database connections. By
         * default we configure 'system' and 'tenant'. The tenant connection
         * is set up automatically by this package.
         *
         * @see src/Database/Connection.php
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-dbsystem-connection-name
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-dbtenant-connection-name
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-dbmigration-connection-name
         */
        'system-connection-name' => env('TENANCY_SYSTEM_CONNECTION_NAME', Connection::DEFAULT_SYSTEM_NAME),
        'tenant-connection-name' => env('TENANCY_TENANT_CONNECTION_NAME', Connection::DEFAULT_TENANT_NAME),
        'tenant-migration-name' => env('TENANCY_MIGRATION_CONNECTION_NAME', Connection::DEFAULT_MIGRATION_NAME),

        /**
         * The tenant division mode specifies to what database websites will be
         * connecting. The default setup is to use a new database per tenant.
         * In case you prefer to use the same database with a table prefix,
         * set the mode to 'prefix'.
         *
         * @see src/Database/Connection.php
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-dbtenant-division-mode
         */
        'tenant-division-mode' => env('TENANCY_DATABASE_DIVISION_MODE', 'database'),

        /**
         * The database password generator takes care of creating a valid hashed
         * string used for tenants to connect to the specific database. Do
         * note that this will only work in 'division modes' that set up
         * a connection to a separate database.
         */
        'password-generator' => Hyn\Tenancy\Generators\Database\DefaultPasswordGenerator::class,

        /**
         * The tenant migrations to be run during creation of a tenant. Specify a directory
         * to run the migrations from.
         *
         * @see https://hyn.readme.io/v3.0/docs/tenancy#section-dbtenant-migrations-path
         */
        'tenant-migrations-path' => false,

        /**
         * Automatically generate a tenant database based on the random id of the
         * website.
         *
         * @see
         * @info set to false to disable.
         */
        'auto-create-tenant-database' => false,

        /**
         * Automatically rename the tenant database when the random id of the
         * website changes. This should not be too common, but in case it happens
         * we automatically want to move databases accordingly.
         *
         * @see
         * @info set to false to disable.
         */
        'auto-rename-tenant-database' => false,

        /**
         * Automatically deletes the tenant specific database and all data
         * contained within.
         *
         * @see
         * @info set to true to enable.
         */
        'auto-delete-tenant-database' => false,
    ],
    'folders' => [
        'config' => [
            /**
             * Merge configuration files from the config directory
             * inside the tenant directory with the global configuration files.
             */
            'enabled' => true,

            /**
             * List of configuration files to ignore, preventing override of crucial
             * application configurations.
             */
            'blacklist' => ['database', 'tenancy', 'webserver'],
        ],
        'routes' => [
            /**
             * Allows adding and overriding URL routes inside the tenant directory.
             */
            'enabled' => true,

            /**
             * Prefix all tenant routes.
             */
            'prefix' => null,
        ],
        'trans' => [
            /**
             * Allows reading translation files from a trans directory inside
             * the tenant directory.
             */
            'enabled' => true,

            /**
             * Will override the global translations with the tenant translations.
             * This is done by overriding the laravel default translator with the new path.
             */
            'override-global' => true,

            /**
             * In case you disabled global override, specify a namespace here to load the
             * tenant translation files with.
             */
            'namespace' => 'tenant',
        ],
        'vendor' => [
            /**
             * Allows using a custom vendor (composer driven) folder inside
             * the tenant directory.
             */
            'enabled' => true,
        ],
        'media' => [
            /**
             * Mounts the assets directory with (static) files for public use.
             */
            'enabled' => true,
        ]
    ]
```

__webserver.php config__

```php

```

---

__Error log__

```text
2017-09-12T14:16:41.944013+00:00 app[queue.1]: [2017-09-12 14:16:41] Processing: App\Jobs\SendEmails

2017-09-12T14:16:41.947301+00:00 app[queue.1]: [2017-09-12 14:16:41] Failed:     App\Jobs\SendEmails

2017-09-12T14:16:41.947578+00:00 app[queue.1]: [2017-09-12 14:16:41] production.ERROR: InvalidArgumentException: Database [tenant] not configured. in /app/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:140

2017-09-12T14:16:41.947580+00:00 app[queue.1]: Stack trace:

2017-09-12T14:16:41.947581+00:00 app[queue.1]: #0 /app/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(103): Illuminate\Database\DatabaseManager->configuration('tenant')

2017-09-12T14:16:41.947582+00:00 app[queue.1]: #1 /app/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(74): Illuminate\Database\DatabaseManager->makeConnection('tenant')

2017-09-12T14:16:41.947583+00:00 app[queue.1]: #2 /app/vendor/laravel/framework/src/Illuminate/Queue/Failed/DatabaseFailedJobProvider.php(115): Illuminate\Database\DatabaseManager->connection('tenant')

2017-09-12T14:16:41.947584+00:00 app[queue.1]: #3 /app/vendor/laravel/framework/src/Illuminate/Queue/Failed/DatabaseFailedJobProvider.php(61): Illuminate\Queue\Failed\DatabaseFailedJobProvider->getTable()

2017-09-12T14:16:41.947585+00:00 app[queue.1]: #4 /app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(187): Illuminate\Queue\Failed\DatabaseFailedJobProvider->log('redis', 'async_quarter', '{"displayName":...', 'InvalidArgument...')

2017-09-12T14:16:41.947586+00:00 app[queue.1]: #5 /app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\Queue\Console\WorkCommand->logFailedJob(Object(Illuminate\Queue\Events\JobFailed))

2017-09-12T14:16:41.947587+00:00 app[queue.1]: #6 /app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(348): Illuminate\Queue\Console\WorkCommand->Illuminate\Queue\Console\{closure}(Object(Illuminate\Queue\Events\JobFailed))

2017-09-12T14:16:41.947588+00:00 app[queue.1]: #7 /app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(199): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Illuminate\\Queu...', Array)

2017-09-12T14:16:41.947588+00:00 app[queue.1]: #8 /app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(172): Illuminate\Events\Dispatcher->dispatch('Illuminate\\Queu...', Array, false)

2017-09-12T14:16:41.947589+00:00 app[queue.1]: #9 /app/vendor/laravel/framework/src/Illuminate/Queue/FailingJob.php(36): Illuminate\Events\Dispatcher->fire(Object(Illuminate\Queue\Events\JobFailed))

2017-09-12T14:16:41.947590+00:00 app[queue.1]: #10 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(420): Illuminate\Queue\FailingJob::handle('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(InvalidArgumentException))

2017-09-12T14:16:41.947590+00:00 app[queue.1]: #11 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\Queue\Worker->failJob('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(InvalidArgumentException))

2017-09-12T14:16:41.947591+00:00 app[queue.1]: #12 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(348): Illuminate\Queue\Worker->markJobAsFailedIfWillExceedMaxAttempts('redis', Object(Illuminate\Queue\Jobs\RedisJob), 1, Object(InvalidArgumentException))

2017-09-12T14:16:41.947592+00:00 app[queue.1]: #13 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(321): Illuminate\Queue\Worker->handleJobException('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions), Object(InvalidArgumentException))

2017-09-12T14:16:41.947593+00:00 app[queue.1]: #14 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(267): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))

2017-09-12T14:16:41.947594+00:00 app[queue.1]: #15 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(113): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))

2017-09-12T14:16:41.947595+00:00 app[queue.1]: #16 /app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'live_high,live_...', Object(Illuminate\Queue\WorkerOptions))

2017-09-12T14:16:41.947595+00:00 app[queue.1]: #17 /app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'live_high,live_...')

2017-09-12T14:16:41.947596+00:00 app[queue.1]: #18 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()

2017-09-12T14:16:41.947598+00:00 app[queue.1]: #19 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)

2017-09-12T14:16:41.947598+00:00 app[queue.1]: #20 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

2017-09-12T14:16:41.947599+00:00 app[queue.1]: #21 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))

2017-09-12T14:16:41.947602+00:00 app[queue.1]: #22 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)

2017-09-12T14:16:41.947603+00:00 app[queue.1]: #23 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)

2017-09-12T14:16:41.947603+00:00 app[queue.1]: #24 /app/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))

2017-09-12T14:16:41.947604+00:00 app[queue.1]: #25 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))

2017-09-12T14:16:41.947605+00:00 app[queue.1]: #26 /app/vendor/symfony/console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2017-09-12T14:16:41.947606+00:00 app[queue.1]: #27 /app/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2017-09-12T14:16:41.947607+00:00 app[queue.1]: #28 /app/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2017-09-12T14:16:41.947607+00:00 app[queue.1]: #29 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2017-09-12T14:16:41.947608+00:00 app[queue.1]: #30 /app/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by luceos** [comment]
Yes a queue job is a new process, it doesn't know anything about the currently active tenant. In order to support this functionality you will have to send some information along about what Tenant you'd like to work with. You could send the Website object along or something.

Ps I highly recommend moving to Laravel 5.5. LTS and 5.x of this package as 4.x (and 3.x) will no longer see active development. I plan on adding functionality to support easier Queue handling in the near future. As a matter of fact, ~~I'll leave this issue open as a reminder~~.

**Comment by hpiMat** [comment]
Hi again,
I intended to send something to the job to allow it to identify the tenant by itself (tried with the customer id which is perfectly working in tinker). Apparently it doesn't work and i got no trace of laravel changing the tenant (Which tends to mean that the line to swap the tenant is not even read and the jobs never launch to begin with). 

I think the problem is appearing when dispatching the job on the queue and not really during the job itself. 

Before that, i got the right tenant. After that supposingly he might find it again with the informations i gave him. I might have to configure redis to log into the tenant database with the tenant information?

Here is my queue config information: 
```php

    /*
    |--------------------------------------------------------------------------
    | Default Queue Driver
    |--------------------------------------------------------------------------
    |
    | Laravel's queue API supports an assortment of back-ends via a single
    | API, giving you convenient access to each back-end using the same
    | syntax for each one. Here you may set the default queue driver.
    |
    | Supported: "sync", "database", "beanstalkd", "sqs", "redis", "null"
    |
    */

    'default' => 'redis',

    /*
    |--------------------------------------------------------------------------
    | Queue Connections
    |--------------------------------------------------------------------------
    |
    | Here you may configure the connection information for each server that
    | is used by your application. A default configuration has been added
    | for each back-end shipped with Laravel. You are free to add more.
    |
    */

    'connections' => [

        'sync' => [
            'driver' => 'sync',
        ],
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => 'name_of_queue',
            'retry_after' => 90,
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Failed Queue Jobs
    |--------------------------------------------------------------------------
    |
    | These options configure the behavior of failed queue job logging so you
    | can control which database and table are used to store the jobs that
    | have failed. You may change them to any database / table you wish.
    |
    */

    'failed' => [
        'database' => env('TENANCY_DEFAULT_CONNECTION', 'tenant'),
        'table' => 'failed_jobs',
    ],

];

I might soon update my packages to get the latest version of laravel and Hyn! Thank you!

**Comment by luceos** [comment]
Can you share the "Job" code, which is dispatched to the queue?

**Comment by hpiMat** [comment]
This is the function to send the job. at this point the tenant is identified and $tenant_id has the right variable in it.
```php 
public function store(Request $request,$path){
        $recipients=$request->recipients;
        $path="pathtofile";
        $tenancy = app(\Hyn\Tenancy\Environment::class);
        $tenant_id=$tenancy->customer()->id;
        $recipients_import = RecipientsImport::create(['path' => $path]);
        dispatch((new ProcessRecipientsImport($recipients_import->id,$recipients,$tenant_id)));
        return $recipients;
    }

```
After that when i dispatch the job. It is not only specific to this particular job since every job i had give the is leading to the same issue and error. Mostly, i lost a the tenant any time i dispatch a job. Maybe the problem is in the driver from the queue.

```php
namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;

use Hyn\Tenancy\Models\Hostname;

use App\RecipientsImport;
use App\Recipient;
use App\Group;
class ProcessRecipientsImport implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 1;
    public $timeout = 60;

    protected $recipients_import;
    protected $recipients;
    protected $reader;
    protected $tenant_id;
    /**
     * Create a new job instance.
     *
     * @param  RecipientsImport $recipients_import
     * @return void
     */
    public function __construct($recipients_import_id,$recipients,$tenant_id)
    {   
        $hostname = Hostname::where("customer_id",$tenant_id)->first();
        $tenancy = app(\Hyn\Tenancy\Environment::class);
        $tenancy->hostname($hostname);
        $this->recipients_import = RecipientsImport::find($recipients_import_id);
        $this->recipients = $recipients;
        $this->reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');
        $this->reader->setReadDataOnly(true);
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {   

        if ($this->recipients_import->hasBeenProcessed()) {
            return true;
        }
        $this->recipients_import->markAsProcessing();
        app('App\Http\Controllers\RecipientController')->markAllRecipientsAsOld();
        $lines = $this->recipients;
        $this->createOrUpdateRecipientsFrom($lines);
        app('App\Http\Controllers\RecipientController')->flushOldRecipients();
        $this->recipients_import->markAsProcessed();
    }

    /**
     * The job failed to process.
     *
     * @param  Exception  $exception
     * @return void
     */
    public function failed(\Exception $exception)
    {
        $this->recipients_import->markAsFailed();
        // TODO, notify a bug tracker?
    }

    /**
     * Create or update recipients from lines.
     *
     * @param  array $lines
     * @return void
     */
    protected function createOrUpdateRecipientsFrom($lines)
    {   
        $recipients = json_decode($lines, true);
        foreach ($recipients as $i=>$line) {
            // Ignore empty lines
            if ($line['Email'] == '') {
                continue;
            }
            $recipient = Recipient::where('email',($line['Email']))->first();
                    if ($recipient == null) {
                        some code
                    } else {
                        some code
                    }
            $recipient->save();
        }

    }   
}

**Comment by luceos** [comment]
Some remarks about your code;

- A customer is **not** a tenant, a website is. Because a request is handled by a website. You should send over the Website or Hostname reference. A hostname is linked to one website, a website is linked to one customer. A customer can have multiple websites and hostnames. As such you're doing a wild guess what tenant you execute your code on.
- Your ioc resolving should be moved to handle, that's the code that is executed inside the Queue. Everything within the construct will be serialized and deserialized. Which means your attempt at setting the tenant setting in the construct fails right now.

**Comment by hpiMat** [comment]
Ok it is working now!
Solution:
Step1: get the hostname from the environment before launching the job:
```php
$tenancy = app(\Hyn\Tenancy\Environment::class);
$hostname=$tenancy->hostname();
dispatch(new Job($hostname));
```
Step2: As you said, you have to get the hostname or the website outside the construct area and put it at the beginning of the handle function. Right at the beginning of the handle function switch the tenant back by getting another time the environment.
```php
public function handle()
    {  
        $tenancy = app(\Hyn\Tenancy\Environment::class);
        $tenancy->hostname($this->hostname);
       //your laravel job is working as intended with the correct tenant.
```

nb: About failed_jobs if you have a table by tenant, you have to change the configuration in the config/queue.php with:

```php 
'failed' => [
        'database' => env('TENANCY_DEFAULT_CONNECTION', 'tenant'),
        'table' => 'failed_jobs',
    ],
```

Thank Luceos for your time and your amazing jobs.

Problem is solved

Matthieu

**Comment by luceos** [comment]
Very glad it actually worked out! Good luck and let me know if you have any further questions.

**Comment by MithrandirDK** [comment]
Sorry to arrive late at this discussion, but I had the same problem and solved it in a general way by overloading the RedisConnector to include website information.

My solution is three-part:
1) A TenantRedisQueue extending RedisQueue to add website meta data to the job payload
2) A TenantRedisConnector extending RedisConnector to use the TenantRedisQueue
3) Registration of the connector and initialisation of the tenant environment in my AppServiceProvider

then I can just configure the app to use my "tenantredis" for queue processing and I don't have to worry about it in my jobs (I have not, however, considered failed_jobs table as I do not presently use that)
TenantRedisQueue:
```
<?php

namespace App\Queue;

use Illuminate\Queue\RedisQueue;
use Illuminate\Support\Facades\Log;
use Predis\Response\ServerException;

class TenantRedisQueue extends RedisQueue
{
    /**
     * Create a payload array from the given job and data.
     *
     * @param  string  $job
     * @param  mixed   $data
     * @param  string  $queue
     * @return array
     */
    protected function createPayloadArray($job, $data = '', $queue = null)
    {
        $website_id = website() ? website()->id : 0;

        return array_merge(parent::createPayloadArray($job, $data, $queue), [
          'website' => $website_id
        ]);
    }

    /**
     * Pop the next job off of the queue.
     *
     * @param  string  $queue
     * @return \Illuminate\Contracts\Queue\Job|null
     */
    public function pop($queue = null)
    {
        try {
            return parent::pop($queue);
        }
        catch (ServerException $e) {
            // Something went wrong with the queue connection
            // Die so supervisord will restart the script
            Log::critical($e->getMessage());
            exit();
        }
    }
}
```
TenantRedisConnector:
```
<?php

namespace App\Queue\Connectors;

use App\Queue\TenantRedisQueue;
use Illuminate\Queue\Connectors\RedisConnector;
use Illuminate\Support\Arr;

class TenantRedisConnector extends RedisConnector
{
    /**
     * Establish a queue connection.
     *
     * @param  array  $config
     * @return \Illuminate\Contracts\Queue\Queue
     */
    public function connect(array $config)
    {
        return new TenantRedisQueue(
          $this->redis, $config['queue'],
          Arr::get($config, 'connection', $this->connection),
          Arr::get($config, 'retry_after', 60)
        );
    }
}
```
And in my AppServiceProvider, I add this method and call it from boot:
```
/**
     * Add TenantRedis Queue connector
     * Set website environment prior to job processing
     */
    private function registerQueue()
    {
        $app = $this->app;
        $this->app['queue']->addConnector('tenantredis', function () use ($app) {
            return new TenantRedisConnector($app['redis']);
        });
        // Set event website environment
        Queue::before(function (JobProcessing $event) {
            $payload = $event->job->payload();
            if (!empty($payload['website'])) {
                // Magic property on event to specify website
                putenv('TENANT=' . $payload['website']);

                // Re-boot application
                $path = base_path('bootstrap') . '/app.php';
                $this->app = null;
                $app = require $path;
                $app->make(Kernel::class)->bootstrap();
                $this->app = $app;
            }
        });
    }
```

This is for hyn/multi-tenant version 2, but the principle could perhaps be re-used?
