### ISSUE TITLE
After moving my code to production, I receive "Database [tenant] not configured." Error

### ISSUE THREAD

**Issue by haljeshi** [hyn/multi-tenant#266]
__Description__

I have been using Hyn for a long time now on my project on my local host which is working fine. After pushing my work to the production online server, I receive the following error when accessing a tenant hostname:

`Database [tenant] not configured.`

So, I have the same code that works on my local machine but is not working on the production server. The only difference I can think of is the database which I have cleaned and truncated before uploading to the server.

I have created the tenant on the production server and not locally and then uploaded the database.

I have tried modifying the config/database.php file and replaced `hyn` connection with `tenant` connection. This has removed the error but now it's using the `tenant.database` property for all my tenants.
..

---

__Actual behavior__

Either getting the above error or when having `tenant` connection in config/database.php using one database for all the tenants
..

__Expected behavior__

Using the tenant database name depending on the accessed hostname
..

---
__Information__

- hyn/multi-tenant version: 2.0
- laravel version: 5.3
- database driver and version: mysql  Ver 15.1 Distrib 10.1.24-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- webserver software and version: Apache/2.4.18 (Ubuntu)
- php version: v7.1.6-1

---

__tenancy.php config__

```php
<?php

return [
    /*
     * Overrule the default tenant directory, where files for tenant websites are stored
     * @default app_storage('/multi-tenant') which resolves to /storage/multi-tenant
     */
    'tenant-directory' => null,

    'db' => [
        /*
         * The name for the system connection, this connection should be configured
         * you can configure this connection within the file config/database.php
         * by adding/editing under connections the key `hyn` or whatever
         * you specify beneath.
         */
        'system-connection-name' => 'hyn',
        /*
         * The name for the tenant connection, this connection will be generated dynamically
         * be aware that specifying this connection name in config/database.php is unneeded,
         * even more, the connection will be overwritten with the tenancy code.
         */
        'tenant-connection-name' => 'tenant',
        /*
         * Specify how you wish to separate the tenant databases from each other. By default
         * we divide them with separate databases. Alternately you can specify `prefix`,
         * which will create tenancy within the same database where tenants are having
         * their own tables with a unique prefix.
         */
        'tenant-division-mode' => 'database',
    ],

    /*
     * Whether to use the middleware.
     * If enabled the hostname will be globally set by the middleware, which ensures the correct
     * tenant data is loaded to be used. Disabling auto detection comes down to you setting
     * the current hostname or tenant by yourself.
     */
    'hostname-detection-middleware' => true,

    /*
     * The queue to run webserver tasks on
     * The specified queue name must have root privileges. If no value specified the default queue is
     * used.
     */
    'queue' => [
        'root' => null,
        'other' => null,
    ],

    /*
     * Specify the tenant specific functionality which should be globally disabled.
     *
     * If base is set to true, no tenant directories are created at all.
     */
    'disallow-for-tenant' => [
        'base'      => false,
        'config'    => false,
        'lang'      => false,
        'media'     => false,
        'providers' => false,
        'routes'    => false,
        'vendor'    => false,
        'views'     => false,
    ],
];

```

__webserver.php config__

```php
<?php

/**
 * All hyn-me/webserver related configuration options.
 *
 * @warning please be advised, read the documentation on http://hyn.me before editing
 *
 * None of the generated configurations will work as long as you don't add the paths to the corresponding webservice
 * configuration file. See documentation for more info.
 */
return [
    'webservers' => ['nginx', 'apache'],

    /*
     * If tenant files should belong to a certain user, set the `default-user` value to that username
     *      - true will generate a username automatically based on the website
     *      - <string> will use the specified existing username for the website
     *      - null will disable generating users
     */
    'default-user' => null,

    /*
     * The group the tenant files should belong to
     */
    'group' => 'www-data',

    /*
     * SSL
     */
    'ssl'   => [
        'path' => storage_path('webserver/ssl'),
    ],
    /*
     * Logging specific settings
     */
    'log' => [
        // path where to store the webserver logs
        'path' => storage_path('logs'),
    ],
    /*
     * Apache
     */
    'apache' => [
        'path' => storage_path('webserver/apache/'),
        // class that runs functionality for this service
        'class'   => 'Hyn\Webserver\Generators\Webserver\Apache',
        'enabled' => true,
        'port'    => [
            'http'  => 80,
            'https' => 443,
        ],
        // path to service daemon, used to verify service exists
        'service' => '/etc/init.d/apache2',
        // how to run actions for this service
        'actions' => [
            'configtest' => 'apache2ctl -t',
            'reload'     => 'apache2ctl graceful',
        ],
        // system wide configuration directory
        'conf' => [
            // location for ubuntu 14.04 systems
            '/etc/apache2/sites-enabled/',
        ],
        // mask for auto-generated config file that includes the tenant configurations
        'mask' => '%s.conf',
        // include format using sprintf to include the location of the storage/webserver/apache directory
        'include' => 'IncludeOptional %s*',
    ],
    /*
     * Nginx
     */
    'nginx' => [
        'path'    => storage_path('webserver/nginx/'),
        'class'   => 'Hyn\Webserver\Generators\Webserver\Nginx',
        'enabled' => true,
        'port'    => [
            'http'  => 80,
            'https' => 443,
        ],
        // path to service daemon, used to verify service exists
        'service' => '/etc/init.d/nginx',
        // how to run actions for this service
        'actions' => [
            'configtest' => '/etc/init.d/nginx configtest',
            'reload'     => '/etc/init.d/nginx reload',
        ],
        'conf'    => ['/etc/nginx/sites-enabled/'],
        'mask'    => '%s.conf',
        'include' => 'include %s*;',
        /*
         * the nginx service depends on fpm
         * during changes we will automatically trigger fpm as well
         */
        'depends' => [
            'fpm',
        ],
    ],
    /*
     * PHP FPM
     */
    'fpm' => [
        'path'    => storage_path('webserver/fpm/'),
        'class'   => 'Hyn\Webserver\Generators\Webserver\Fpm',
        'enabled' => true,
        'conf'    => [
            '/etc/php7/fpm/pool.d/'
        ],
        // path to service daemon, used to verify service exists
        'service' => '/etc/init.d/php7-fpm',
        // how to run actions for this service
        'actions' => [
            'configtest' => '/etc/init.d/php7-fpm -t',
            'reload'     => '/etc/init.d/php7-fpm reload',
        ],
        'mask'    => '%s.conf',
        'include' => 'include=%s*;',
        /*
         * base modifier for fpm pool port
         * @example if base is 9000, will generate pool file for website Id 5 with port 9005
         * @info this port is used in Nginx configurations for the PHP proxy
         */
        'port' => 9000,
    ],
];

```

---

__Error log__

```text
[2017-10-01 11:32:03] local.ERROR: InvalidArgumentException: Database [tenant] not configured. in /var/www/test1/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:239
Stack trace:
#0 /var/www/test1/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(158): Illuminate\Database\DatabaseManager->getConfig('tenant')
#1 /var/www/test1/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(68): Illuminate\Database\DatabaseManager->makeConnection('tenant')
#2 /var/www/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3351): Illuminate\Database\DatabaseManager->connection('tenant')
#3 /var/www/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3317): Illuminate\Database\Eloquent\Model::resolveConnection('tenant')
#4 /var/www/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1861): Illuminate\Database\Eloquent\Model->getConnection()
#5 /var/www/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1834): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#6 /var/www/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1804): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#7 /var/www/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(631): Illuminate\Database\Eloquent\Model->newQuery()
#8 /var/www/test1/app/Model/Admin/Opportunity.php(16): Illuminate\Database\Eloquent\Model::all()
#9 /var/www/test1/app/Http/Controllers/Admin/OpportunityController.php(21): App\Model\Admin\Opportunity::getAll()
#10 [internal function]: App\Http\Controllers\Admin\OpportunityController->index()
#11 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#12 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
#13 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Admin\OpportunityController), 'index')
#14 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#15 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/test1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/test1/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/test1/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/test1/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/test1/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#38 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#39 /var/www/test1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#40 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/test1/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/test1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/test1/vendor/hyn/multi-tenant/src/Tenancy/Middleware/HostnameMiddleware.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Hyn\Tenancy\Middleware\HostnameMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/test1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/test1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/test1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /var/www/test1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 /var/www/test1/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 {main}  

```

**Comment by luceos** [comment]
Being quite a while since I've actively looked at 2.x, but from what I can tell it would seem that your tenant connection is not activated. One reason for this can be that you have no websites configured as the [code uses](https://github.com/hyn/multi-tenant/blob/2.x/src/Tenancy/TenancyEnvironment.php#L52) the website of the currently identified hostname to switch the connection to.

Let me know if this is true.

**Comment by haljeshi** [comment]
Thanks for your response.

I went to check my base database to make sure that the website is present and it was there. But when I looked into my hostnames table, I found something strange.

The hostname itself is wrong and when I updated it in the database, it worked again.

Thank you very much for your help. Now the problem is resolved.
