### ISSUE TITLE
Undefined index: driver when sending notification to new created tenant

### ISSUE THREAD

**Issue by michaeldaly** [hyn/multi-tenant#378]
I have come across an issue when trying to send a welcome email after I set up a new tenant in my system.

I have put my controller and notification code below which will hopefully be straight forward to replicate for testing purposes.

I am interested to see if anyone else is having this issue too and what the fix might be?

Here is the error I am getting:

![screen shot 2018-02-05 at 22 08 34](https://user-images.githubusercontent.com/8914893/35831349-35c38bac-0ac1-11e8-8cfd-8eea08761aa9.png)

**Stack Trace**
```
[2018-02-05 21:51:23] local.ERROR: Undefined index: driver {"userId":14,"email":"hello@michaeldaly.me","exception":"[object] (ErrorException(code: 0): Undefined index: driver at /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:115)
[stacktrace]
#0 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(115): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/Users/mike/Sit...', 115, Array)
#1 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(74): Illuminate\\Database\\DatabaseManager->makeConnection('tenant')
#2 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBrokerManager.php(96): Illuminate\\Database\\DatabaseManager->connection('tenant')
#3 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBrokerManager.php(74): Illuminate\\Auth\\Passwords\\PasswordBrokerManager->createTokenRepository(Array)
#4 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBrokerManager.php(51): Illuminate\\Auth\\Passwords\\PasswordBrokerManager->resolve('users')
#5 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Auth\\Passwords\\PasswordBrokerManager->broker()
#6 /Users/mike/Sites/openpci/app/Notifications/TenantCreated.php(23): Illuminate\\Support\\Facades\\Facade::__callStatic('broker', Array)
#7 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(50): App\\Notifications\\TenantCreated->toMail(Object(App\\User))
#8 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\\Notifications\\Channels\\MailChannel->send(Object(App\\User), Object(App\\Notifications\\TenantCreated))
#9 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(App\\User), '986a1f45-4c49-4...', Object(App\\Notifications\\TenantCreated), 'mail')
#10 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\\Notifications\\NotificationSender->sendNow(Object(Illuminate\\Database\\Eloquent\\Collection), Object(App\\Notifications\\TenantCreated))
#11 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(35): Illuminate\\Notifications\\NotificationSender->send(Object(Illuminate\\Database\\Eloquent\\Collection), Object(App\\Notifications\\TenantCreated))
#12 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send(Object(App\\User), Object(App\\Notifications\\TenantCreated))
#13 /Users/mike/Sites/openpci/app/Http/Controllers/TenantsController.php(50): App\\User->notify(Object(App\\Notifications\\TenantCreated))
#14 [internal function]: App\\Http\\Controllers\\TenantsController->store(Object(Illuminate\\Http\\Request))
#15 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#16 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#17 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\TenantsController), 'store')
#18 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#19 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#20 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/mike/Sites/openpci/vendor/spatie/laravel-permission/src/Middlewares/RoleMiddleware.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Spatie\\Permission\\Middlewares\\RoleMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'super-admin')
#23 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#48 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#49 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#50 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#51 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/mike/Sites/openpci/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/mike/Sites/openpci/vendor/hyn/multi-tenant/src/Middleware/EagerIdentification.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Hyn\\Tenancy\\Middleware\\EagerIdentification->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/mike/Sites/openpci/vendor/hyn/multi-tenant/src/Middleware/HostnameActions.php(72): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Hyn\\Tenancy\\Middleware\\HostnameActions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#75 /Users/mike/Sites/openpci/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#76 /Users/mike/Sites/openpci/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#77 /Users/mike/.composer/vendor/laravel/valet/server.php(133): require('/Users/mike/Sit...')
#78 {main}
"} 
```

**Tenant Controller**

```
<?php

namespace App\Http\Controllers;

use App\Notifications\TenantCreated;
use App\User;
use Hyn\Tenancy\Environment;
use Hyn\Tenancy\Contracts\Repositories\CustomerRepository;
use Hyn\Tenancy\Contracts\Repositories\HostnameRepository;
use Hyn\Tenancy\Contracts\Repositories\WebsiteRepository;
use Hyn\Tenancy\Models\Customer;
use Hyn\Tenancy\Models\Hostname;
use Hyn\Tenancy\Models\Website;
use Illuminate\Console\Command;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class TenantsController extends Controller
{
    public function store(Request $request)
    {
        $tenantName = 'My Tenant Name';
        $slug = 'my-tenant-name';
        $name = 'First Tenant';
        $email = 'test@example.com';

        if ($this->tenantExists($name, $email)) {
             // REPORT ERROR
             return;
        }

        $this->registerTenant($tenantName, $slug, $name, $email);

        $password = str_random();
        $admin = $this->addAdmin($name, $email, $password);
        $admin->notify(new TenantCreated());

        return redirect('/admin/tenants');
    }

    private function tenantExists($name, $email)
    {
        return Customer::where('name', $name)->orWhere('email', $email)->exists();
    }

    private function registerTenant($tenantName, $tenantSlug, $name, $email)
    {
        // create a customer
        $customer = new Customer;
        $customer->name = $name;
        $customer->email = $email;
        app(CustomerRepository::class)->create($customer);

        // associate the customer with a website
        $website = new Website;
        $website->customer()->associate($customer);
        $website->name = $tenantName;
        app(WebsiteRepository::class)->create($website);

        // associate the website with a hostname
        $hostname = new Hostname;
        $baseUrl = config('app.url_base');
        $hostname->fqdn = "{$tenantSlug}.{$baseUrl}";
        $hostname->customer()->associate($customer);
        app(HostnameRepository::class)->attach($hostname, $website);

        return $hostname;
    }

    private function addAdmin($name, $email, $password)
    {
        return User::create(['name' => $name, 'email' => $email, 'password' => Hash::make($password)]);
    }
}

```

**Notification**

```
namespace App\Notifications;

use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Facades\Password;

class TenantCreated extends Notification
{
    public function __construct()
    {

    }

    public function via()
    {
        return ['mail'];
    }

    public function toMail($notifiable)
    {
        $token = Password::broker()->createToken($notifiable);

        $resetUrl = "https://myurl.dev/password/reset/{$token}";

        $app = config('app.name');

        return (new MailMessage())
            ->subject("{$app} Invitation")
            ->greeting("Hello {$notifiable->name},")
            ->line("You have been invited to use {$app}!")
            ->line('To get started you need to set a password.')
            ->action('Set password', $resetUrl);
    }
}
```

**Comment by luceos** [comment]
Does your `database.php` have a `driver` in the `system` connection?

**Comment by michaeldaly** [comment]
Yes, I have the following:

```
'system' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
```

**Comment by michaeldaly** [comment]
A bit more information....If I don't call the `registerTenant` method, I don't get the error.

So, it looks like something inside `registerTenant` is creating the problem.

**Comment by luceos** [comment]
Where is the listener firing the Notification?

**Comment by michaeldaly** [comment]
I haven't set up a listener for the notification. Just following the instructions here: https://laravel.com/docs/5.5/notifications#sending-notifications

I didn't think I needed a listener to use the standard notifications as described in that article?

**Comment by luceos** [comment]
Okay can you test in your TenantController what the value is behind `config('database.connections.tenant')`?

**Comment by michaeldaly** [comment]
I will run this code this evening and let you know.

**Comment by michaeldaly** [comment]
I have checked and here are the results:

 - `null` before I call `$this->registerTenant`
 - `[]` after I call it but before I call `$this->addAdmin()`

**Comment by Xerixe** [comment]
I'm pretty sure I had this problem before and it was because the hostname was not set.

Try this

```
$hostname = $this->registerTenant($tenantName, $slug, $name, $email);
app(Environment::class)->hostname($hostname);
```

**Comment by michaeldaly** [comment]
I have previously tried that code but for some reason it is looking for the tenant database rather than the system database.

Here is the error I was getting:

![screen shot 2018-02-06 at 20 40 39](https://user-images.githubusercontent.com/8914893/35883114-215274f4-0b7e-11e8-8f93-6edb0bb7b824.png)

**Comment by Xerixe** [comment]
Well, that just means your tenant database does not have the `password_resets` table. 

Is your `User` model a system model or tenant model? From what I can tell, you want it to be a tenant model, hence why `password_resets` needs to be in the tenant database.

**Comment by michaeldaly** [comment]
sorry I don't think I explained properly. My users table is against the system table and I am managing my users there so I can provide access across multiple sites if I need to.

My users, hostnames, customers, and websites are all created as expected in the system database without any issues. The issue comes when I try to call the notification to send a welcome/set password email to the user.

So, the user is added correctly as well as their other tenant information (which means I am connecting to the the system database) but when I try to send the email, it is trying to set the `password_reset` token against the tenant database which is incorrect for my use-case.

**Comment by michaeldaly** [comment]
My user model looks like this:

```
namespace App;

use Hyn\Tenancy\Traits\UsesSystemConnection;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, UsesSystemConnection, HasRoles;

    /**
     * The attributes that are mass assignable.
     *w
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

**Comment by michaeldaly** [comment]
It would be great if someone could add a controller and a notification in a similar way to what I am doing, to see if they also get the exception.

If we can identify whether this is a config issue, or a bug in the package, it will help me to start working on finding the right fix.

**Comment by luceos** [comment]
@michaeldalyuk i think we still need to follow up on this. I'll book some hours asap to dive into open issues that require manual testing.

**Comment by Krato** [comment]
For me it works after add `UsesSystemConnection` trait.

**Comment by spacemudd** [comment]
Maybe unrelated but I'm receiving the same error in phpunit when creating a new `website` using the `WebsiteRepository`.

It fails right when I use `$this->assertDatabaseHas('users', ...)` where the `users` table is in the main db.

**Comment by luceos** [comment]
I think I'll need the minimum steps to reproduce here.

**Comment by bkintanar** [comment]
I tried to replicate this issue and failed. It is currently working as desired.

# Hello test,

You have been invited to use Laravel!

To get started you need to set a password.

Set password: https://myurl.dev/password/reset/2c04f6a74641bd5ca587db04a573175ebe3349a5a589d263d4f98c6e7157ab21

Regards,Laravel

If you’re having trouble clicking the "Set password" button, copy and paste the URL below
into your web browser: [https://myurl.dev/password/reset/2c04f6a74641bd5ca587db04a573175ebe3349a5a589d263d4f98c6e7157ab21](https://myurl.dev/password/reset/2c04f6a74641bd5ca587db04a573175ebe3349a5a589d263d4f98c6e7157ab21)

© 2018 Laravel. All rights reserved.

**Comment by spacemudd** [comment]
Just to give a final update on what fixed my issued:

1. `app(Environment::class)->hostname($hostname);` after creating hostname as @Xerixe suggested.
    - (w/o it, my code fails `ErrorException: Undefined index: driver` because _tenant_ connection is `[]`)
2. In phpunit, must specifically set the connection to the main db when asserting. 
     - (w/o setting it, php tries asserting in _tenant_ db hence getting `table uuid.users doesnt exist`)

P.S. I'm not using the 'Customer' logic but implementing my own way of associating a 'Company' to the hostname which I feel might be the reason the environment hostname is not being correctly loaded? But oh well. My code looks like:

        $company = Company::where('id', $id)->first(); // UsesSystemConnection trait.

        $website = new \Hyn\Tenancy\Models\Website();
        $this->websiteRepo->create($website);

        $hostname = new Hostname();
        $hostname->fqdn = $appDomain;
        $this->hostnameRepo->attach($hostname, $website);

        $company->database = $website->uuid;
        $company->save();

        app(Environment::class)->hostname($hostname);   // w/o, tenant connection would be set to [].
        \App\Tenant\Models\User::create($initialUser);  // Copy user from main db to tenant db.

Test:

```
       $this->assertDatabaseHas('users', [
            'name' => $data['name'],
        ], env('DB_CONNECTION')); // system

       $this->assertDatabaseHas('users', [
            'name' => $data['name'],
        ]); // connects to tenant db.
```

Thank you for the package. It's neat as hell.

**Comment by luceos** [comment]
1. Makes sense that a newly created tenant has not been set as active, imagine you are creating tenants in batches. Glad that @Xerixe pointed out the ability to force an active tenant to be set.
2. I'm not sure what connection the assertion takes per default, but it would seem to be it would use the one set as default in Laravel?

Related to the Customer object, that's not an issue. It's going to be dropped from the package in the upcoming 5.2 release anyway 👍 

> Thank you for the package. It's neat as hell.

Can I quote you 😊 

Thanks for the extensive report back, totally appreciate that.

**Comment by spacemudd** [comment]
>imagine you are creating tenants in batches.

Oh! That's actually really helpful to not have them load up. I get it.

>I'm not sure what connection the assertion takes per default, but it would seem to be it would use the one set as default in Laravel?

I thought so too, and it does take the default when not using `  app(Environment::class)->hostname()`.

Though from my tests I _believe_ it asserts against the last connection Laravel connects to.

>Can I quote you 😊

Heck yes. 😂

**Comment by mah3uz** [comment]
@luceos I got same error after upgrade to 5.2 from 5.1
Initial user creation says 
`Undefined index: driver`
My user table is in tenant database and I `use UsesTenantConnection` trait on User Model.
Am I missing something? or it's a bug?

**Comment by luceos** [comment]
@mah3uz please create a new issue with a backtrace and your configuration.

**Comment by howlowck** [comment]
I might've found the issue.. if someone (like me or anyone following [this blog post](https://medium.com/@ashokgelal/a-full-featured-multi-tenant-app-with-laravel-part-1-4049a3cc229d)) uses `app(Environment::class)->hostname($hostname)` to switch the tenant, the connection is never set because `ConnectsTenants` is not subscribing to `Events\Hostnames\Switched`, the event that `hostname` fires.

-----------
@luceos, if you'd like, I can make a PR and add `Events\Hostnames\Switched` event to the `ConnectsTenants` subscription, and add `switchHostname` method, to get the website from hostname 

**OR**  

change the event that `Environment->hostname` fires from `Events\Hostnames\Switched($hostname)` to `Events\Websites\Switched($hostname->website)` as it appears nothing is subscribing to that event.

--------

In the meantime, `app(Environment::class)->tenant($website)` fixes the error because that fires the `Events\Websites\Switched` event.

**Comment by fletch3555** [comment]
That is a change between 5.1 and 5.2, and is mentioned in the upgrade guide in the docs.  `Environment->hostname` no longer sets the tenant, for exactly the reason you describe.  This was a conscious decision, so no change/PR is necessary.

**Comment by luceos** [comment]
I'm locking this issue as it starts to off road into different versions and different topics. I'd prefer you only comment to an existing issue if you're sure this is related to you and your current hyn package version.
