### ISSUE TITLE
Integrity constraint violation with TENANCY_DATABASE_DIVISION_MODE=prefix

### ISSUE THREAD

**Issue by jmcerrejon** [hyn/multi-tenant#451]
I make a first tenant with _php artisan store:create demodemo@gmail.com_ with no hassle. When I make a new one using _php artisan store:create demo2 demo2@gmail.com_, I get the following issue:

```
 Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-293_f5' (SQL: alter table `2_model_has_permissions` add constraint `model_has_permissions_permission_id_foreign` foreign key (`permission_id`) references `2_permissions` (`id`) on delete cascade)
```

- hyn/multi-tenant version: 4.1.11
- laravel version: 5.6.21
- database driver and version: -
- webserver software and version: Nginx 
- php version: 7.1.16

---

__tenancy.php config__

```php
<?php

/*
 * This file is part of the hyn/multi-tenant package.
 *
 * (c) Daniël Klabbers <daniel@klabbers.email>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @see https://laravel-tenancy.com
 * @see https://github.com/hyn/multi-tenant
 */

use Hyn\Tenancy\Database\Connection;

return [
    'models' => [
        /**
         * Specify different models to be used for the global, system database
         * connection. These are also used in their relationships. Models
         * used have to implement their respective contracts and
         * either extend the SystemModel or use the trait
         * UsesSystemConnection.
         */

        // Must implement \Hyn\Tenancy\Contracts\Customer
        'customer' => \Hyn\Tenancy\Models\Customer::class,

        // Must implement \Hyn\Tenancy\Contracts\Hostname
        'hostname' => \Hyn\Tenancy\Models\Hostname::class,

        // Must implement \Hyn\Tenancy\Contracts\Website
        'website' => \Hyn\Tenancy\Models\Website::class
    ],
    'website' => [
        /**
         * Each website has a short random hash that identifies this entity
         * to the application. By default this id is randomized and fully
         * auto-generated. In case you want to force your own logic for
         * when you need to have a better overview of the complete
         * tenant folder structure, disable this and implement
         * your own id generation logic.
         */
        'disable-random-id' => false,

        /**
         * The random Id generator is responsible for creating the hash as mentioned
         * above. You can override what generator to use by modifying this value
         * in the configuration.
         *
         * @warn This won't work if disable-random-id is true.
         */
        'random-id-generator' => Hyn\Tenancy\Generators\Uuid\ShaGenerator::class,

        /**
         * Enable this flag in case you're using a driver that does not support
         * database username or database name with a length of more than 32 characters.
         *
         * This should be enabled for MySQL, but not for MariaDB and PostgreSQL.
         */
        'uuid-limit-length-to-32' => env('LIMIT_UUID_LENGTH_32', false),

        /**
         * Specify the disk you configured in the filesystems.php file where to store
         * the tenant specific files, including media, packages, routes and other
         * files for this particular website.
         *
         * @info If not set, will revert to the default filesystem.
         */
        'disk' => null,

        /**
         * Automatically generate a tenant directory based on the random id of the
         * website. Uses the above disk to store files to override system-wide
         * files.
         *
         * @info set to false to disable.
         */
        'auto-create-tenant-directory' => true,

        /**
         * Automatically rename the tenant directory when the random id of the
         * website changes. This should not be too common, but in case it happens
         * we automatically want to move files accordingly.
         *
         * @info set to false to disable.
         */
        'auto-rename-tenant-directory' => true,

        /**
         * Automatically deletes the tenant specific directory and all files
         * contained within.
         *
         * @see
         * @info set to true to enable.
         */
        'auto-delete-tenant-directory' => env('AUTO_DELETE_TENANT_DIRECTORY', false),

        /**
         * Time to cache websites in minutes. Set to false to disable.
         */
        'cache' => 10,
    ],
    'hostname' => [
        /**
         * If you want the multi tenant application to fall back to a default
         * hostname/website in case the requested hostname was not found
         * in the database, complete in detail the default hostname.
         *
         * @warn this must be a FQDN, these have no protocol or path!
         */
        'default' => env('TENANCY_DEFAULT_HOSTNAME'),
        /**
         * The package is able to identify the requested hostname by itself,
         * disable to get full control (and responsibility) over hostname
         * identification. The hostname identification is needed to
         * set a specific website as currently active.
         *
         * @see src/Jobs/HostnameIdentification.php
         */
        'auto-identification' => env('TENANCY_AUTO_HOSTNAME_IDENTIFICATION', true),

        /**
         * In case you want to have the tenancy environment set up early,
         * enable this flag. This will run the tenant identification
         * inside a middleware. This will eager load tenancy.
         *
         * A good use case is when you have set "tenant" as the default
         * database connection.
         */
        'early-identification' => env('TENANCY_EARLY_IDENTIFICATION', false),

        /**
         * Abort application execution in case no hostname was identified. This will throw a
         * 404 not found in case the tenant hostname was not resolved.
         */
        'abort-without-identified-hostname' => false,

        /**
         * Time to cache hostnames in minutes. Set to false to disable.
         */
        'cache' => 1,
    ],
    'db' => [
        /**
         * The default connection to use; this overrules the Laravel database.default
         * configuration setting. In Laravel this is normally configured to 'mysql'.
         * You can set a environment variable to override the default database
         * connection to - for instance - the tenant connection 'tenant'.
         */
        'default' => env('TENANCY_DEFAULT_CONNECTION'),
        /**
         * Used to give names to the system and tenant database connections. By
         * default we configure 'system' and 'tenant'. The tenant connection
         * is set up automatically by this package.
         *
         * @see src/Database/Connection.php
         * @var system-connection-name The database connection name to use for the global/system database.
         * @var tenant-connection-name The database connection name to use for the tenant database.
         */
        'system-connection-name' => env('TENANCY_SYSTEM_CONNECTION_NAME', Connection::DEFAULT_SYSTEM_NAME),
        'tenant-connection-name' => env('TENANCY_TENANT_CONNECTION_NAME', Connection::DEFAULT_TENANT_NAME),

        /**
         * The tenant division mode specifies to what database websites will be
         * connecting. The default setup is to use a new database per tenant.
         * In case you prefer to use the same database with a table prefix,
         * set the mode to 'prefix'.
         *
         * @see src/Database/Connection.php
         */
        'tenant-division-mode' => env('TENANCY_DATABASE_DIVISION_MODE', 'database'),

        /**
         * The database password generator takes care of creating a valid hashed
         * string used for tenants to connect to the specific database. Do
         * note that this will only work in 'division modes' that set up
         * a connection to a separate database.
         */
        'password-generator' => Hyn\Tenancy\Generators\Database\DefaultPasswordGenerator::class,

        /**
         * The tenant migrations to be run during creation of a tenant. Specify a directory
         * to run the migrations from. If specified these migrations will be executed
         * whenever a new tenant is created.
         *
         * @info set to false to disable auto migrating.
         *
         * @warn this has to be an absolute path, feel free to use helper methods like
         * base_path() or database_path() to set this up.
         */
        'tenant-migrations-path' => database_path('migrations/tenant'),

        /**
         * Seeds the newly created tenant database based on this Seeder.
         *
         * @info requires tenant-migrations-path to be in use.
         *
         * @warn specify a valid fully qualified class name.
         * @example App\Seeders\AdminSeeder::class
         */
        'tenant-seed-class' => StoreDatabaseSeeder::class,

        /**
         * Automatically generate a tenant database based on the random id of the
         * website.
         *
         * @info set to false to disable.
         */
        'auto-create-tenant-database' => true,

        /**
         * Automatically rename the tenant database when the random id of the
         * website changes. This should not be too common, but in case it happens
         * we automatically want to move databases accordingly.
         *
         * @info set to false to disable.
         */
        'auto-rename-tenant-database' => true,

        /**
         * Automatically deletes the tenant specific database and all data
         * contained within.
         *
         * @info set to true to enable.
         */
        'auto-delete-tenant-database' => env('AUTO_DELETE_TENANT_DATABASE', false),
    ],
    'folders' => [
        'config' => [
            /**
             * Merge configuration files from the config directory
             * inside the tenant directory with the global configuration files.
             */
            'enabled' => true,

            /**
             * List of configuration files to ignore, preventing override of crucial
             * application configurations.
             */
            'blacklist' => ['database', 'tenancy', 'webserver'],
        ],
        'routes' => [
            /**
             * Allows adding and overriding URL routes inside the tenant directory.
             */
            'enabled' => true,

            /**
             * Prefix all tenant routes.
             */
            'prefix' => null,
        ],
        'trans' => [
            /**
             * Allows reading translation files from a trans directory inside
             * the tenant directory.
             */
            'enabled' => true,

            /**
             * Will override the global translations with the tenant translations.
             * This is done by overriding the laravel default translator with the new path.
             */
            'override-global' => true,

            /**
             * In case you disabled global override, specify a namespace here to load the
             * tenant translation files with.
             */
            'namespace' => 'tenant',
        ],
        'vendor' => [
            /**
             * Allows using a custom vendor (composer driven) folder inside
             * the tenant directory.
             */
            'enabled' => true,
        ],
        'media' => [
            /**
             * Mounts the assets directory with (static) files for public use.
             */
            'enabled' => true,
        ]
    ]
];

```

---

__Error log__

```text
[2018-05-09 19:39:16] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-2b7_25' (SQL: alter table `2_model_has_permissions` add constraint `model_has_permissions_permission_id_foreign` foreign key (`permission_id`) references `2_permissions` (`id`) on delete cascade) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-2b7_25' (SQL: alter table `2_model_has_permissions` add constraint `model_has_permissions_permission_id_foreign` foreign key (`permission_id`) references `2_permissions` (`id`) on delete cascade) at ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-2b7_25' at ..[my_website_full_path]_../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:143, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-2b7_25' at ..[my_website_full_path]_../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141)
[stacktrace]
#0 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('alter table `2_...', Array, Object(Closure))
#1 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('alter table `2_...', Array, Object(Closure))
#2 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(88): Illuminate\\Database\\Connection->statement('alter table `2_...')
#3 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(252): Illuminate\\Database\\Schema\\Blueprint->build(Object(Illuminate\\Database\\MySqlConnection), Object(Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar))
#4 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(165): Illuminate\\Database\\Schema\\Builder->build(Object(Illuminate\\Database\\Schema\\Blueprint))
#5 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Database\\Schema\\Builder->create('model_has_permi...', Object(Closure))
#6 ..[my_website_full_path]_../database/migrations/tenant/2018_03_02_000001_create_permission_tables.php(42): Illuminate\\Support\\Facades\\Facade::__callStatic('create', Array)
#7 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(359): CreatePermissionTables->up()
#8 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(366): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#9 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(177): Illuminate\\Database\\Migrations\\Migrator->runMigration(Object(CreatePermissionTables), 'up')
#10 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(146): Illuminate\\Database\\Migrations\\Migrator->runUp('/Users/ulysess/...', 1, false)
#11 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(95): Illuminate\\Database\\Migrations\\Migrator->runPending(Array, Array)
#12 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(70): Illuminate\\Database\\Migrations\\Migrator->run(Array, Array)
#13 ..[my_website_full_path]_../vendor/hyn/multi-tenant/src/Traits/MutatesMigrationCommands.php(58): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#14 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Support/Collection.php(397): Hyn\\Tenancy\\Database\\Console\\Migrations\\MigrateCommand->Hyn\\Tenancy\\Traits\\{closure}(Object(Hyn\\Tenancy\\Models\\Website), 0)
#15 ..[my_website_full_path]_../vendor/hyn/multi-tenant/src/Traits/AddWebsiteFilterOnCommand.php(31): Illuminate\\Support\\Collection->each(Object(Closure))
#16 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): Hyn\\Tenancy\\Database\\Console\\Migrations\\MigrateCommand->Hyn\\Tenancy\\Traits\\{closure}(Object(Illuminate\\Database\\Eloquent\\Collection), 1)
#17 ..[my_website_full_path]_../vendor/hyn/multi-tenant/src/Traits/AddWebsiteFilterOnCommand.php(32): Illuminate\\Database\\Eloquent\\Builder->chunk(10, Object(Closure))
#18 ..[my_website_full_path]_../vendor/hyn/multi-tenant/src/Traits/MutatesMigrationCommands.php(61): Hyn\\Tenancy\\Database\\Console\\Migrations\\MigrateCommand->processHandle(Object(Closure))
#19 [internal function]: Hyn\\Tenancy\\Database\\Console\\Migrations\\MigrateCommand->handle()
#20 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#21 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#25 ..[my_website_full_path]_../vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#26 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#27 ..[my_website_full_path]_../vendor/symfony/console/Application.php(865): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#28 ..[my_website_full_path]_../vendor/symfony/console/Application.php(241): Symfony\\Component\\Console\\Application->doRunCommand(Object(Hyn\\Tenancy\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#29 ..[my_website_full_path]_../vendor/symfony/console/Application.php(143): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#30 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#31 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Console/Application.php(186): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#32 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(250): Illuminate\\Console\\Application->call('tenancy:migrate', Array, NULL)
#33 ..[my_website_full_path]_../vendor/hyn/multi-tenant/src/Database/Connection.php(224): Illuminate\\Foundation\\Console\\Kernel->call('tenancy:migrate', Array)
#34 ..[my_website_full_path]_../vendor/hyn/multi-tenant/src/Listeners/Database/MigratesTenants.php(52): Hyn\\Tenancy\\Database\\Connection->migrate(Object(Hyn\\Tenancy\\Models\\Website), '/Users/ulysess/...')
#35 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Hyn\\Tenancy\\Listeners\\Database\\MigratesTenants->migrate(Object(Hyn\\Tenancy\\Events\\Websites\\Created))
#36 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Hyn\\\\Tenancy\\\\Eve...', Array)
#37 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(182): Illuminate\\Events\\Dispatcher->dispatch('Hyn\\\\Tenancy\\\\Eve...', Array, false)
#38 ..[my_website_full_path]_../vendor/hyn/multi-tenant/src/Traits/DispatchesEvents.php(29): Illuminate\\Events\\Dispatcher->fire(Object(Hyn\\Tenancy\\Events\\Websites\\Created), Array)
#39 ..[my_website_full_path]_../vendor/hyn/multi-tenant/src/Repositories/WebsiteRepository.php(95): Hyn\\Tenancy\\Repositories\\WebsiteRepository->emitEvent(Object(Hyn\\Tenancy\\Events\\Websites\\Created))
#40 ..[my_website_full_path]_../app/Store.php(51): Hyn\\Tenancy\\Repositories\\WebsiteRepository->create(Object(Hyn\\Tenancy\\Models\\Website))
#41 ..[my_website_full_path]_../app/Console/Commands/CreateStore.php(27): App\\Store::createFrom('demo1', 'tienda_demo1@cm...', 'Tienda demo1')
#42 [internal function]: App\\Console\\Commands\\CreateStore->handle()
#43 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#44 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#45 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#46 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#47 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#48 ..[my_website_full_path]_../vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#49 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#50 ..[my_website_full_path]_../vendor/symfony/console/Application.php(865): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 ..[my_website_full_path]_../vendor/symfony/console/Application.php(241): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\CreateStore), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#52 ..[my_website_full_path]_../vendor/symfony/console/Application.php(143): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#53 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#54 ..[my_website_full_path]_../vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#55 ..[my_website_full_path]_../artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#56 {main}
"} 
```

__.env__

```php
...
TENANCY_DEFAULT_HOSTNAME=demo
TENANCY_DATABASE_DIVISION_MODE=prefix
LIMIT_UUID_LENGTH_32=true
AUTO_DELETE_TENANT_DIRECTORY=true
AUTO_DELETE_TENANT_DATABASE=true
...
```

__Composer.json__

```
...
    "require": {
        "php": ">=7.1.3",
        "fideloper/proxy": "~4.0",
        "hyn/multi-tenant": "^5.1",
        "jeroennoten/laravel-adminlte": "^1.23",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "~1.0",
        "spatie/laravel-backup": "^5.5",
        "spatie/laravel-permission": "^2.9",
        "yajra/laravel-datatables-oracle": "~8.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "laravel/dusk": "^3.0",
        "mockery/mockery": "~1.0",
        "nunomaduro/collision": "~2.0",
        "phpunit/phpunit": "~7.0",
        "symfony/thanks": "^1.0"
    },
...
```

**Comment by luceos** [comment]
> tenancy doesn't work with foreign key constraints because laravel makes it up automatically based on logic we don't mutate yet

from discord

Seems like we either need to add this functionality or drop the prefix option completely.

**Comment by luceos** [comment]
So the cause here is that you have to give each constraint a unique name. As `2018_03_02_000001_create_permission_tables` is not a migration this package manages I'd suggest modifying the migration to make the constraint random (if possible based on the tenant id?).

In the end, this is not something we can solve. You can use the second argument in the `foreign` method:

```php
    /**
     * Specify a foreign key for the table.
     *
     * @param  string|array  $columns
     * @param  string  $name
     * @return \Illuminate\Support\Fluent
     */
    public function foreign($columns, $name = null)
    {
        return $this->indexCommand('foreign', $columns, $name);
    }
```

**Comment by xmarkclx** [comment]
Is there a way to get the tenant ID on the migrations code?

**Comment by luceos** [comment]
Yes resolve the `Tenant` contract out of ioc:

```php
$tenant = app(\Hyn\Tenancy\Contracts\Tenant::class);
```

Then get the uuid:

```php
$tenant->uuid;
```
