### ISSUE TITLE
Nginx vhost file not being generated

### ISSUE THREAD

**Issue by TheTechnoMan** [hyn/multi-tenant#462]
__Description__

Even though the creation of nginx vhost files is enabled, it won't create them. 

It however creates apache vhost files as expected inthe storage/app/tenancy/webserver/apache2 dir.

---
__Information__

- hyn/multi-tenant version: 5.1.12
- laravel version: 5.6.22
- php version: 7.1.11

**Comment by luceos** [comment]
Post your config please.

**Comment by TheTechnoMan** [comment]
Pretty much the standard config

```
<?php

/*
 * This file is part of the hyn/multi-tenant package.
 *
 * (c) Daniël Klabbers <daniel@klabbers.email>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @see https://laravel-tenancy.com
 * @see https://github.com/hyn/multi-tenant
 */

return [

    /**
     * Apache2 is one of the most widely adopted webserver packages available.
     *
     * @see http://httpd.apache.org/docs/
     * @see https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu
     */
    'apache2' => [
        /**
         * Whether the integration with Apache2 is currently active.
         */
        'enabled' => true,

        /**
         * Define the ports of your Apache service.
         */
        'ports' => [
            /**
             * HTTP, non-SSL port.
             *
             * @default 80
             */
            'http' => 80,
            /**
             * HTTPS, SSL port.
             *
             * @default 443
             */
            'https' => 443
        ],

        /**
         * The generator taking care of hooking into the Apache services and files.
         */
        'generator' => \Hyn\Tenancy\Generators\Webserver\Vhost\ApacheGenerator::class,

        /**
         * The view that holds the vhost configuration template.
         */
        'view' => 'tenancy.generators::webserver.apache.vhost',

        /**
         * Specify the disk you configured in the filesystems.php file where to store
         * the tenant vhost configuration files.
         *
         * @info If not set, will revert to the default filesystem.
         */
        'disk' => null,

        'paths' => [

            /**
             * Location where vhost configuration files can be found.
             */
            'vhost-files' => [
                '/etc/apache2/sites-enabled/'
            ],

            /**
             * Actions to run to work with the Apache2 service.
             */
            'actions' => [
                /**
                 * Action that asserts Apache2 is installed.
                 */
                'exists' => '/etc/init.d/apache2',
                /**
                 * Action to run to test the apache configuration.
                 */
                'test-config' => "ls",
                /**
                 * Action to run to reload the apache service.
                 */
                'reload' => 'B:\laragon\laragon.exe reload apache'
            ]
        ]
    ],

    /**
     * Nginx webserver support.
     *
     * @see http://nginx.org
     */
    'nginx' => [
        /**
         * Whether the integration with nginx is currently active.
         */
        'true' => true,

        /**
         * The php sock to be used.
         */
        'php-sock' => 'unix:/var/run/php/php7.0-fpm.sock',

        /**
         * Define the ports of your nginx service.
         */
        'ports' => [
            /**
             * HTTP, non-SSL port.
             *
             * @default 80
             */
            'http' => 80,
            /**
             * HTTPS, SSL port.
             *
             * @default 443
             */
            'https' => 443
        ],

        /**
         * The generator taking care of hooking into the nginx services and files.
         */
        'generator' => \Hyn\Tenancy\Generators\Webserver\Vhost\NginxGenerator::class,

        /**
         * The view that holds the vhost configuration template.
         */
        'view' => 'tenancy.generators::webserver.nginx.vhost',

        /**
         * Specify the disk you configured in the filesystems.php file where to store
         * the tenant vhost configuration files.
         *
         * @info If not set, will revert to the default filesystem.
         */
        'disk' => null,

        'paths' => [

            /**
             * Location where vhost configuration files can be found.
             */
            'vhost-files' => [
                '/etc/nginx/sites-enabled/'
            ],

            /**
             * Actions to run to work with the Nginx service.
             */
            'actions' => [
                /**
                 * Action that asserts nginx is installed.
                 */
                #'exists' => '/etc/init.d/nginx',
                'exists' => 'ls',
                /**
                 * Action to run to test the nginx configuration.
                 */
                #'test-config' => '/etc/init.d/nginx configtest',
                'test-config' => 'ls',
                /**
                 * Action to run to reload the nginx service.
                 */
                #'reload' => 'systemctl restart nginx'
                'reload' => 'ls'
            ]
        ]
    ]
];

```

**Comment by luceos** [comment]
Are you seeing errors in your laravel.log file or with APP_DEBUG enabled?

Can you run the following through artisan tinker:

```
config('filesystems.disks.tenancy-webserver-nginx');
```

Can you explain your set up?

**Comment by TheTechnoMan** [comment]
```
Psy Shell v0.9.3 (PHP 7.1.11 — cli) by Justin Hilemanan
>>> config('filesystems.disks.tenancy-webserver-nginx');
=> [
     "driver" => "local",
     "root" => "B:\laragon\www\Laravel\Main\storage\app/tenancy/webserver/nginx",
   ]
>>>

```

There is indeed a log entry being created:

```
[2018-05-22 17:51:50] local.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'tenant'@'localhost' (using password: NO) {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'tenant'@'localhost' (using password: NO) at B:\\laragon\\www\\Laravel\\Main\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'tenant'@'localhost' (using password: NO) at B:\\laragon\\www\\Laravel\\Main\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)
[stacktrace]
#0 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php(65): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=127....', 'tenant', '', Array)
#1 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=127....', 'tenant', '', Array)
#2 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=127....', Array, Array)
#3 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\ConnectionFactory.php(183): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(915): call_user_func(Object(Closure))
#6 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(940): Illuminate\\Database\\Connection->getPdo()
#7 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(399): Illuminate\\Database\\Connection->getReadPdo()
#8 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(325): Illuminate\\Database\\Connection->getPdoForSelect(true)
#9 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)
#10 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#11 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(333): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#12 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(1909): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#13 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(1894): Illuminate\\Database\\Query\\Builder->runSelect()
#14 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(483): Illuminate\\Database\\Query\\Builder->get(Array)
#15 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(467): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#16 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1504): Illuminate\\Database\\Eloquent\\Builder->get()
#17 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1516): Illuminate\\Database\\Eloquent\\Model->__call('get', Array)
#18 B:\\laragon\\www\\Laravel\\Main\\app\\Repositories\\DbConfigRepository.php(25): Illuminate\\Database\\Eloquent\\Model::__callStatic('get', Array)
#19 B:\\laragon\\www\\Laravel\\Main\\app\\Providers\\AppServiceProvider.php(23): App\\Repositories\\DbConfigRepository->get()
#20 [internal function]: App\\Providers\\AppServiceProvider->boot()
#21 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#22 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(794): Illuminate\\Container\\Container->call(Array)
#26 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(777): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\AppServiceProvider))
#27 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\AppServiceProvider), 39)
#28 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(778): array_walk(Array, Object(Closure))
#29 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#30 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(206): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#31 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(297): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#32 B:\\laragon\\www\\Laravel\\Main\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(120): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#33 B:\\laragon\\www\\Laravel\\Main\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 {main}
"} 

```

So it appears that the connecting is being changed at some point (would have to be after the apache vhost file creation).

Please let me know what information would be relevant, so that I can add it.

Thanks a lot

**Comment by luceos** [comment]
Okay let's stick to one issue 👍

**Comment by paulcanning** [comment]
Why is this issue closed? There was no resolution. I too am getting empty NGINX conf files being generated.

**Comment by luceos** [comment]
@paulcanning please stick to your own reported issue, every environment can be different. We'll do our best to assist everyone.

**Comment by javierrivarola** [comment]
Why is this issue closed? There was no resolution. I too am getting empty NGINX conf files being generated. x2

**Comment by fletch3555** [comment]
@javierrivarola I will refer you to @luceos' comment
