### ISSUE TITLE
Error if create website

### ISSUE THREAD

**Issue by aBuder** [hyn/multi-tenant#578]
Hi, I get an error if I create an new website.

![bildschirmfoto 2018-08-12 um 19 07 54](https://user-images.githubusercontent.com/1265139/44004458-439a4fd2-9e63-11e8-818a-a99a94b0e498.png)

```php
 $request->merge(['hostname', $request->get('hostname','admin') .'.' . env('APP_URL_BASE')]);
 
        // set validation rules
        $request->validate([
            'hostname' => 'required|unique:hostnames,fqdn'
        ]);
 
        // create website
        $website = new Website();
        app(WebsiteRepository::class)->create($website);
 
        // create hostname
        $hostname = new Hostname();
        $hostname->fqdn = $request->get('hostname')  .'.' . env('APP_URL_BASE');
        app(HostnameRepository::class)->attach($hostname, $website);
 
        // create tenancy
        $tenancy = app(Environment::class);
        $tenancy->hostname($hostname); $tenancy->hostname(); // resolves $hostname as currently active hostname
        $tenancy->tenant($website); // switches the tenant and reconfigures the app
        $tenancy->website(); // resolves $website
        $tenancy->tenant(); // resolves $website
        $tenancy->identifyHostname(); // resets resolving $hostname by using the Request
 
        // create initial admin user
        $admin = new User();
        $admin->name = $request->session()->get('forename') .' ' . $request->session()->get('surname');
        $admin->salutation = $request->session()->get('salutation');
        $admin->forename = $request->session()->get('forename');
        $admin->surname = $request->session()->get('surname');

```

**Comment by fletch3555** [comment]
Is this actual code, or just various attempts you've made? Because this looks weird and unnecessary.
```
// create tenancy
$tenancy = app(Environment::class);
$tenancy->hostname($hostname); $tenancy->hostname(); // resolves $hostname as currently active hostname
$tenancy->tenant($website); // switches the tenant and reconfigures the app
$tenancy->website(); // resolves $website
$tenancy->tenant(); // resolves $website
$tenancy->identifyHostname(); // resets resolving $hostname by using the Request
```

----

This is the old (5.1) way of identifying tenants.  5.2 no longer uses this, so while it will change the identified hostname, it's effectively a useless call.  Also, not sure what the 2nd call to `hostname()` is intended for, since it will only return the currently identified hostname, and since you don't store or use the return value, it's not doing anything. (https://github.com/hyn/multi-tenant/blob/5.x/src/Environment.php#L94)
```
$tenancy->hostname($hostname); $tenancy->hostname(); // resolves $hostname as currently active hostname
```
This line is absolutely necessary (in 5.2... method doesn't exist in 5.1)
```
$tenancy->tenant($website); // switches the tenant and reconfigures the app
```
This simply returns the currently identified Hostname's associated Website, but since you don't store or use the return value, it's not doing anything (https://github.com/hyn/multi-tenant/blob/5.x/src/Environment.php#L107)
```
$tenancy->website(); // resolves $website
```
This simply returns the current tenant, but since you don't store or use the return value, it's not doing anything (https://github.com/hyn/multi-tenant/blob/5.x/src/Environment.php#L120)
```
$tenancy->tenant(); // resolves $website
```
This line will attempt to identify the hostname again using information from the request, then set it properly with `->tenant()` (https://github.com/hyn/multi-tenant/blob/5.x/src/Environment.php#L76)
```
$tenancy->identifyHostname(); // resets resolving $hostname by using the Request
```

**Comment by aBuder** [comment]
I would like to create an new tenant and would switch to new tenant. I don't know where my error is.

<img width="2523" alt="bildschirmfoto 2018-08-19 um 09 59 15" src="https://user-images.githubusercontent.com/1265139/44306817-9250f080-a396-11e8-8a98-574753430029.png">

```log
[2018-08-19 08:07:09] local.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `41711e06d58848d7aef6d959663ced92`@'localhost' IDENTIFIED BY 'c008' at line 1 (SQL: CREATE USER IF NOT EXISTS `41711e06d58848d7aef6d959663ced92`@'localhost' IDENTIFIED BY 'c0080bcc7594557d02c1f6549571d38d') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `41711e06d58848d7aef6d959663ced92`@'localhost' IDENTIFIED BY 'c008' at line 1 (SQL: CREATE USER IF NOT EXISTS `41711e06d58848d7aef6d959663ced92`@'localhost' IDENTIFIED BY 'c0080bcc7594557d02c1f6549571d38d') at /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `41711e06d58848d7aef6d959663ced92`@'localhost' IDENTIFIED BY 'c008' at line 1 at /usr/local/www/apache24/noexec/butterfly-app.net/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `41711e06d58848d7aef6d959663ced92`@'localhost' IDENTIFIED BY 'c008' at line 1 at /usr/local/www/apache24/noexec/butterfly-app.net/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80)
[stacktrace]
#0 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('CREATE USER IF ...', Array, Object(Closure))
#1 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('CREATE USER IF ...', Array, Object(Closure))
#2 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/hyn/multi-tenant/src/Generators/Webserver/Database/Drivers/MariaDB.php(38): Illuminate\\Database\\Connection->statement('CREATE USER IF ...')
#3 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/hyn/multi-tenant/src/Generators/Webserver/Database/Drivers/MariaDB.php(51): Hyn\\Tenancy\\Generators\\Webserver\\Database\\Drivers\\MariaDB->Hyn\\Tenancy\\Generators\\Webserver\\Database\\Drivers\\{closure}(Object(Illuminate\\Database\\MySqlConnection))
#4 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): Hyn\\Tenancy\\Generators\\Webserver\\Database\\Drivers\\MariaDB->Hyn\\Tenancy\\Generators\\Webserver\\Database\\Drivers\\{closure}(Object(Illuminate\\Database\\MySqlConnection))
#5 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/hyn/multi-tenant/src/Generators/Webserver/Database/Drivers/MariaDB.php(52): Illuminate\\Database\\Connection->transaction(Object(Closure))
#6 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/hyn/multi-tenant/src/Generators/Webserver/Database/DatabaseGenerator.php(101): Hyn\\Tenancy\\Generators\\Webserver\\Database\\Drivers\\MariaDB->created(Object(Hyn\\Tenancy\\Events\\Websites\\Created), Array, Object(Hyn\\Tenancy\\Database\\Connection))
#7 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Hyn\\Tenancy\\Generators\\Webserver\\Database\\DatabaseGenerator->created(Object(Hyn\\Tenancy\\Events\\Websites\\Created))
#8 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Hyn\\\\Tenancy\\\\Eve...', Array)
#9 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(182): Illuminate\\Events\\Dispatcher->dispatch('Hyn\\\\Tenancy\\\\Eve...', Array, false)
#10 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/hyn/multi-tenant/src/Traits/DispatchesEvents.php(29): Illuminate\\Events\\Dispatcher->fire(Object(Hyn\\Tenancy\\Events\\Websites\\Created), Array)
#11 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/hyn/multi-tenant/src/Repositories/WebsiteRepository.php(95): Hyn\\Tenancy\\Repositories\\WebsiteRepository->emitEvent(Object(Hyn\\Tenancy\\Events\\Websites\\Created))
#12 /usr/local/www/apache24/noexec/butterfly-app.net/app/Http/Controllers/SetupController.php(142): Hyn\\Tenancy\\Repositories\\WebsiteRepository->create(Object(Hyn\\Tenancy\\Models\\Website))
#13 [internal function]: App\\Http\\Controllers\\SetupController->storeCloud(Object(Illuminate\\Http\\Request))
#14 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#15 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('storeCloud', Array)
#16 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\SetupController), 'storeCloud')
#17 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#18 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#19 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#41 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#42 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#43 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#44 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#45 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/hyn/multi-tenant/src/Middleware/EagerIdentification.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Hyn\\Tenancy\\Middleware\\EagerIdentification->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/hyn/multi-tenant/src/Middleware/HostnameActions.php(76): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Hyn\\Tenancy\\Middleware\\HostnameActions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#68 /usr/local/www/apache24/noexec/butterfly-app.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#69 /usr/local/www/apache24/noexec/butterfly-app.net/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#70 {main}
"} 
```

```php
        // set validation rules
        $request->validate([
            'hostname' => 'required|unique:hostnames,fqdn'
        ]);

        // create website
        $website = new Website();
        app(WebsiteRepository::class)->create($website);

        // create hostname
        $hostname = new Hostname();
        $hostname->fqdn = $request->get('hostname')  .'.' . env('APP_URL_BASE');
        app(HostnameRepository::class)->attach($hostname, $website);

        // create tenancy
        $tenancy = app(Environment::class);
        $tenancy->tenant($website);

        // create initial admin user
        $admin = new User();
        $admin->name = $request->session()->get('forename') .' ' . $request->session()->get('surname');
        $admin->salutation = $request->session()->get('salutation');
        $admin->forename = $request->session()->get('forename');
        $admin->surname = $request->session()->get('surname');
        $admin->email = $request->session()->get('email');
        $admin->password = Hash::make($request->session()->get('password'));
        $admin->save();
        $admin->assignRole('Admin');
        $admin->save();

        // send welcome email to admin user
        $admin->notify(new TenantCreated($hostname, $admin));

        // set licence to installed
        $key = $request->session()->get('key');
        $licence = Licence::query()->where('key', $key)->first();
        $licence->hostname_id = $hostname->id;
        $licence->installed = true;
        $licence->save();

        // redirect to tenant subdomain to new tenant
        return redirect()->away('https://'. $request->get('hostname','admin') . '.' . env('APP_URL_BASE'));

```

**Comment by aBuder** [comment]
I identify that the error is `IF NOT EXISTS `. On my local machine I installed 
`Ver 15.1 Distrib 10.3.7-MariaDB, for osx10.13 (x86_64) using readline 5.1`

on webserver I see
`Server version: 5.6.35 Source distribution`

**Comment by luceos** [comment]
@aBuder your webserver runs what database? MySQL 5.6?

**Comment by aBuder** [comment]
@luceos correct there runs MySQL Server version: 5.6.35 Source distribution

**Comment by luceos** [comment]
From the [requirements](https://laravel-tenancy.com/docs/hyn/5.2/requirements): MySQL 5.7+, MariaDB 10.1.13+

Your server doesn't have the right MySQL version.
