### ISSUE TITLE
Connection detection not work anymore from commit 47c2909

### ISSUE THREAD

**Issue by HpiGuillaume** [hyn/multi-tenant#680]
__Description__

Hello, just to give you feedback about your last commit.  I'v make a composer update and passed "hyn/multi-tenant" from "5.x-dev c9d3377" to "5.x-dev 47c2909" then my test route (using EnforceTenancy Middleware) doesn't giving me a Tenant connection anymore.

---

__Actual behavior__

I've make a basic route for my tests who:
- use middleware "EnforceTenancy" (just make ```php         Config::set('database.default', 'tenant');```)
- get a `User` (so on a tenant DB)
- return it in JSON

__Expected behavior__

I expect a json array of the selected `User` of the desired tenant

---
__Information__

The only diff was my `composer update` who update the hyn package from "5.x-dev c9d3377" to "5.x-dev 47c2909"

---

__Error log__

```text
[2018-12-03 13:31:54] local.ERROR: Database [tenant] not configured. {"exception":"[object] (InvalidArgumentException(code: 0): Database [tenant] not configured. at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:140)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(103): Illuminate\\Database\\DatabaseManager->configuration('tenant')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(74): Illuminate\\Database\\DatabaseManager->makeConnection('tenant')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1201): Illuminate\\Database\\DatabaseManager->connection('tenant')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1167): Illuminate\\Database\\Eloquent\\Model::resolveConnection('tenant')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(997): Illuminate\\Database\\Eloquent\\Model->getConnection()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(912): Illuminate\\Database\\Eloquent\\Model->newBaseQueryBuilder()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(950): Illuminate\\Database\\Eloquent\\Model->newModelQuery()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(901): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(891): Illuminate\\Database\\Eloquent\\Model->newQuery()
#9 /var/www/html/routes/web.php(32): Illuminate\\Database\\Eloquent\\Model::query()
...
```

**Comment by luceos** [comment]
Are you sure a tenant actually exists? Setting the default connection to `tenant` without a tenant being identified causes the error you posted.. Especially in cli/artisan where this package has no way of auto identifying tenants.

**Comment by HpiGuillaume** [comment]
Hello,

Thanks for the response.

Yes I had more than 1 tenant create at this time.

**Comment by HpiGuillaume** [comment]
Hello, with the last update, so commit d73f03f, tested today, I don't have the issue. So I closed it :d

**Comment by HpiGuillaume** [comment]
Got the issue in Staging environment.
Sorry to have close-it and reopn-it, my bad I hadn't clean properly my local environment.

**Comment by HpiGuillaume** [comment]
Hello,

I've found a way to avoid this error.
In my EnforeTenancy Middleware I've add: `app(Environment::class)->tenant($currentWebsite);`

**Comment by luceos** [comment]
Do you have early identification enabled in your configuration?

**Comment by HpiGuillaume** [comment]
Hello,

Yes it's activate in the config.

To place in my context I have a specific identification of customer system:
I use a custom header `X-CUSTOMER-NAME` that I identify in `AppServiceProvider::register()`. In the same place I hydrate the env `TENANCY_CURRENT_HOSTNAME` with the good hostname of identified customer. Then the request pass into the middleware `EnforceTenancy.php`.

I don't think my method to hydrate the env `TENANCY_CURRENT_HOSTNAME` is wrong and nether too late in the workflow to be managed by the middlewares of laravel-tenancy `\Hyn\Tenancy\Middleware\EagerIdentification::class`and `\Hyn\Tenancy\Middleware\HostnameActions::class`.
