### ISSUE TITLE
Bash installation error

### ISSUE THREAD

**Issue by Krato** [hyn/multi-tenant#72]
Hi again. 

Sorry but when I use or bash installer.sh on Ubuntu I get an error on final setup.

I install `supervisor`and `beanstalk` also. 

Laravel log:
```log
[2016-05-13 11:09:43] production.ERROR: ErrorException: Array to string conversion in /var/www/vendor/pda/pheanstalk/src/Command/UseCommand.php:40
Stack trace:
#0 /var/www/vendor/pda/pheanstalk/src/Command/UseCommand.php(40): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Array to string...', '/var/www/vendor...', 40, Array)
#1 /var/www/vendor/pda/pheanstalk/src/Connection.php(100): Pheanstalk\Command\UseCommand->getCommandLine()
#2 /var/www/vendor/pda/pheanstalk/src/Pheanstalk.php(396): Pheanstalk\Connection->dispatchCommand(Object(Pheanstalk\Command\UseCommand))
#3 /var/www/vendor/pda/pheanstalk/src/Pheanstalk.php(347): Pheanstalk\Pheanstalk->_dispatch(Object(Pheanstalk\Command\UseCommand))
#4 /var/www/vendor/laravel/framework/src/Illuminate/Queue/BeanstalkdQueue.php(71): Pheanstalk\Pheanstalk->useTube(Array)
#5 /var/www/vendor/laravel/framework/src/Illuminate/Queue/BeanstalkdQueue.php(58): Illuminate\Queue\BeanstalkdQueue->pushRaw('{"job":"Illumin...', Array)
#6 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(33): Illuminate\Queue\BeanstalkdQueue->push(Object(Hyn\Webserver\Commands\WebserverCommand), '', Array)
#7 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(261): Illuminate\Queue\Queue->pushOn(Array, Object(Hyn\Webserver\Commands\WebserverCommand))
#8 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(243): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\BeanstalkdQueue), Object(Hyn\Webserver\Commands\WebserverCommand))
#9 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(175): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(Hyn\Webserver\Commands\WebserverCommand))
#10 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Hyn\Webserver\Commands\WebserverCommand))
#11 /var/www/vendor/hyn/webserver/src/Observers/WebsiteObserver.php(15): Hyn\Webserver\Observers\WebsiteObserver->dispatch(Object(Hyn\Webserver\Commands\WebserverCommand))
#12 [internal function]: Hyn\Webserver\Observers\WebsiteObserver->created(Object(Hyn\MultiTenant\Models\Website))
#13 /var/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Hyn\MultiTenant\Models\Website))
#15 /var/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1650): Illuminate\Events\Dispatcher->fire('eloquent.create...', Array)
#17 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1578): Illuminate\Database\Eloquent\Model->fireModelEvent('eloquent.create...', false)
#18 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1452): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#19 /var/www/vendor/hyn/framework/src/Models/AbstractModel.php(96): Illuminate\Database\Eloquent\Model->save(Array)
#20 /var/www/vendor/hyn/framework/src/Repositories/BaseRepository.php(47): Hyn\Framework\Models\AbstractModel->save()
#21 /var/www/vendor/hyn/multi-tenant/src/Commands/SetupCommand.php(145): Hyn\Framework\Repositories\BaseRepository->create(Array)
#22 [internal function]: Hyn\MultiTenant\Commands\SetupCommand->handle()
#23 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#24 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#25 /var/www/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/vendor/symfony/console/Application.php(841): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Hyn\MultiTenant\Commands\SetupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 {main}  
```

How to fix?

Thanks

**Comment by Krato** [comment]
Ok, I think the problem is on create queue. This line: ` $this->onQueue(config('multi-tenant.queue'));` fails when you call webserver command from artisan. Error: 
```                  
  [ErrorException]            
  Array to string conversion 
```

**Comment by Luceos** [comment]
You're right the config key is an array:

https://github.com/hyn/multi-tenant/blob/master/config/multi-tenant.php#L47

**Comment by Krato** [comment]
I change `beanstalk` to `sync` and work. Will work this package also with `sync`?

**Comment by Luceos** [comment]
> I change beanstalk to sync and work. Will work this package also with sync?

Yes.

Can you answer my previous question if you would:

> Where did you find `$this->onQueue(config('multi-tenant.queue'));`? Which is causing the issue?

**Comment by Krato** [comment]
Sorry for late answer. I found it here: https://github.com/hyn/framework/blob/5b31b94f0a2023002d494568f82a7c0b170082c6/src/Commands/AbstractCommand.php

**Comment by Luceos** [comment]
But it says something totally different there it says `$this->onQueue(config('multi-tenant.queue.other'));` with the `other` added. Are you running the last version?

**Comment by Krato** [comment]
YEs, I updated and now works. Thanks!
