### ISSUE TITLE
 Bad Ip connection assigned Using Laradock (docker)

### ISSUE THREAD

**Issue by Punksolid** [hyn/multi-tenant#722]
The default instalation works fine, it creates the database user and the database hashed, but when it starts with the migration of the tenant fails. 

When doing 
```php
        $website = new Website();
        app(WebsiteRepository::class)->create($website);
```
Gives me this error
```
   Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'da258c0890a4443badd69f95d9150a9b'@'172.19.0.1' (using password: YES) (SQL: select * from information_schema.tables where table_schema = da258c0890a4443badd69f95d9150a9b and table_name = migrations)

```
I have configured and used fine putting the DB_HOST as 127.0.01, that's the host that it should be using also to connect to the tenants, but somehow it shows 172.19.0.1, it looks that that its the ip given/configured to MariaDB inside his docker container.    
..

---
__Information__

- hyn/multi-tenant version: 5.3.1
- laravel version: 5.7.27
- database driver and version: MariaDB-1:10.3.12+maria~bionic
- webserver software and version: embebed php server
- php version: 7.3.2

---
all default configuration of tenancy.php config file

no webserver activated

```text
[2019-02-21 03:11:03] local.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'e0b307be008048f8ac8dcad094917b46'@'172.19.0.1' (using password: YES) (SQL: select * from information_schema.tables where table_schema = e0b307be008048f8ac8dcad094917b46 and table_name = migrations) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'e0b307be008048f8ac8dcad094917b46'@'172.19.0.1' (using password: YES) (SQL: select * from information_schema.tables where table_schema = e0b307be008048f8ac8dcad094917b46 and table_name = migrations) at /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'e0b307be008048f8ac8dcad094917b46'@'172.19.0.1' (using password: YES) at /home/ze/projects/trm/neotrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'e0b307be008048f8ac8dcad094917b46'@'172.19.0.1' (using password: YES) at /home/ze/projects/trm/neotrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)
[stacktrace]
#0 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#1 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from i...', Array, Object(Closure))
#2 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select('select * from i...', Array)
#3 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable('migrations')
#4 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(556): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#5 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(91): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#6 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(63): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#7 /home/ze/projects/trm/neotrm/vendor/hyn/multi-tenant/src/Traits/MutatesMigrationCommands.php(57): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#8 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Support/Collection.php(419): Hyn\\Tenancy\\Database\\Console\\Migrations\\MigrateCommand->Hyn\\Tenancy\\Traits\\{closure}(Object(Hyn\\Tenancy\\Models\\Website), 0)
#9 /home/ze/projects/trm/neotrm/vendor/hyn/multi-tenant/src/Traits/AddWebsiteFilterOnCommand.php(31): Illuminate\\Support\\Collection->each(Object(Closure))
#10 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): Hyn\\Tenancy\\Database\\Console\\Migrations\\MigrateCommand->Hyn\\Tenancy\\Traits\\{closure}(Object(Illuminate\\Database\\Eloquent\\Collection), 1)
#11 /home/ze/projects/trm/neotrm/vendor/hyn/multi-tenant/src/Traits/AddWebsiteFilterOnCommand.php(32): Illuminate\\Database\\Eloquent\\Builder->chunk(10, Object(Closure))
#12 /home/ze/projects/trm/neotrm/vendor/hyn/multi-tenant/src/Traits/MutatesMigrationCommands.php(60): Hyn\\Tenancy\\Database\\Console\\Migrations\\MigrateCommand->processHandle(Object(Closure))
#13 [internal function]: Hyn\\Tenancy\\Database\\Console\\Migrations\\MigrateCommand->handle()
#14 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#19 /home/ze/projects/trm/neotrm/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#20 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#21 /home/ze/projects/trm/neotrm/vendor/symfony/console/Application.php(901): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#22 /home/ze/projects/trm/neotrm/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Hyn\\Tenancy\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#23 /home/ze/projects/trm/neotrm/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#24 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#25 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Console/Application.php(188): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#26 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(250): Illuminate\\Console\\Application->call('tenancy:migrate', Array, NULL)
#27 /home/ze/projects/trm/neotrm/vendor/hyn/multi-tenant/src/Database/Connection.php(266): Illuminate\\Foundation\\Console\\Kernel->call('tenancy:migrate', Array)
#28 /home/ze/projects/trm/neotrm/vendor/hyn/multi-tenant/src/Listeners/Database/MigratesTenants.php(53): Hyn\\Tenancy\\Database\\Connection->migrate(Object(Hyn\\Tenancy\\Models\\Website), '/home/ze/projec...')
#29 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Hyn\\Tenancy\\Listeners\\Database\\MigratesTenants->migrate(Object(Hyn\\Tenancy\\Events\\Websites\\Created))
#30 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Hyn\\\\Tenancy\\\\Eve...', Array)
#31 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(182): Illuminate\\Events\\Dispatcher->dispatch('Hyn\\\\Tenancy\\\\Eve...', Array, false)
#32 /home/ze/projects/trm/neotrm/vendor/hyn/multi-tenant/src/Traits/DispatchesEvents.php(29): Illuminate\\Events\\Dispatcher->fire(Object(Hyn\\Tenancy\\Events\\Websites\\Created), Array)
#33 /home/ze/projects/trm/neotrm/vendor/hyn/multi-tenant/src/Repositories/WebsiteRepository.php(95): Hyn\\Tenancy\\Repositories\\WebsiteRepository->emitEvent(Object(Hyn\\Tenancy\\Events\\Websites\\Created))
#34 /home/ze/projects/trm/neotrm/app/Console/Commands/NewAccount.php(45): Hyn\\Tenancy\\Repositories\\WebsiteRepository->create(Object(Hyn\\Tenancy\\Models\\Website))
#35 [internal function]: App\\Console\\Commands\\NewAccount->handle()
#36 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#37 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#38 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#39 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#40 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#41 /home/ze/projects/trm/neotrm/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#42 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#43 /home/ze/projects/trm/neotrm/vendor/symfony/console/Application.php(901): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 /home/ze/projects/trm/neotrm/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\NewAccount), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /home/ze/projects/trm/neotrm/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 /home/ze/projects/trm/neotrm/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 {main}
"} 

```

So instead of fixing this, is there a way to specify that I want to use the main database credentials for tenants too? There is no intention to give users access directly anyways

Thank you. Looks like the most robust package for laravel tenants multidatabase so far.

**Comment by luceos** [comment]
The problem is that for the tenant connection it will copy over the existing system configuration and then apply changes to username, password and database. In order to rectify that for virtualised environments you'd best listen to the Configuring or Configured events and set the values as you see fit.

**Comment by shahzad-sarwar** [comment]
change the following in .env to work with laradock, besides have you configured the system database?

DB_HOST=mariadb

**Comment by Punksolid** [comment]
This is awesome, thanks @luceos. So I explain what I did

I created a listener with php artisan make:listener UseMainConnectionListener
```php
class UseMainConnectionListener
{
    /**
     * Handle the event.
     *
     * @param  ConfigurationLoaded  $event
     * @return void
     */
    public function handle(ConfigurationLoaded $event)
    {
        $event->configuration["username"] = config("database.connections.system.username");
        $event->configuration["password"] = config("database.connections.system.password");
    }
}
```
Then registered on EventServiceProvider.php

```php
    protected $listen = [
        'App\Events\Event' => [
            'App\Listeners\EventListener',
        ],
        ConfigurationLoaded::class => [
            UseMainConnectionListener::class
        ]
    ];
```

and now connects using the main connection, creates the database, and starts the migrations.
