### ISSUE TITLE
Model Binding Don't Work With Tenant Identification By Middleware

### ISSUE THREAD

**Issue by Punksolid** [hyn/multi-tenant#768]
I have multi-tenant working very well by sending the tenant uuid and switching environment in a middleware. Stores, paginates and so on. But I just saw that Model Binding isn't working because it tries to use the main system table, the model uses UsesTenantConnection and I even specified in the 'force-tenant-connection' key in the config file. 

I already have my controllers using model bindings  and that's where it fails to identify that it is a tenant model. If I do it inside the method it works just fine.

It's supposed that model binding should work.

How do I specify the environment to work with model bindings? I'm sending the tenant id in the headers of every request.
..

- hyn/multi-tenant version:5.4.1
- laravel version: 5.8
- database driver and version: MariadB 10.3
- webserver software and version: php embebed server 
- php version: 7.3.3

---

__tenancy.php config__

```php
<?php

use Hyn\Tenancy\Database\Connection;

return [

    'key' => env('TENANCY_KEY', env('APP_KEY')),

    'models' => [

        // Must implement \Hyn\Tenancy\Contracts\Hostname
        'hostname' => \Hyn\Tenancy\Models\Hostname::class,

//        'website' => \Hyn\Tenancy\Models\Website::class // original
        'website' => \App\Account::class //  local personalized
    ],

    'middleware' => [
        // The eager identification middleware.
        \Hyn\Tenancy\Middleware\EagerIdentification::class,

        // The hostname actions middleware (redirects, https, maintenance).
        \Hyn\Tenancy\Middleware\HostnameActions::class,
    ],
    'website' => [
        'disable-random-id' => false,
        'random-id-generator' => Hyn\Tenancy\Generators\Uuid\ShaGenerator::class,
        'uuid-limit-length-to-32' => env('LIMIT_UUID_LENGTH_32', false),
        'disk' => null,
        'auto-create-tenant-directory' => true,
        'auto-rename-tenant-directory' => true,
        'auto-delete-tenant-directory' => false,
        'cache' => 10,
    ],
    'hostname' => [
        'default' => env('TENANCY_DEFAULT_HOSTNAME'),
        'auto-identification' => env('TENANCY_AUTO_HOSTNAME_IDENTIFICATION', true),
        'early-identification' => env('TENANCY_EARLY_IDENTIFICATION', true),
        'abort-without-identified-hostname' => env('TENANCY_ABORT_WITHOUT_HOSTNAME', false),
        'cache' => 10,
        'update-app-url' => false,
    ],
    'db' => [

        'default' => env('TENANCY_DEFAULT_CONNECTION'),
        'system-connection-name' => env('TENANCY_SYSTEM_CONNECTION_NAME', Connection::DEFAULT_SYSTEM_NAME),
        'tenant-connection-name' => env('TENANCY_TENANT_CONNECTION_NAME', Connection::DEFAULT_TENANT_NAME),

        'tenant-division-mode' => env('TENANCY_DATABASE_DIVISION_MODE', 'database'),

        'password-generator' => Hyn\Tenancy\Generators\Database\DefaultPasswordGenerator::class,


        'tenant-migrations-path' => database_path('migrations/tenant'),
//        'tenant-migrations-path' => false,

        'tenant-seed-class' => CreateTenantPermissionsSeeder::class,
//        'tenant-seed-class' => MainSeedTenants::class,
//      eg an admin seeder under `app/Seeders/AdminSeeder.php`:
//        'tenant-seed-class' => App\Seeders\AdminSeeder::class,

        'auto-create-tenant-database' => true,
        'auto-create-tenant-database-user' => false,
        'tenant-database-user-privileges' => null,
        'auto-rename-tenant-database' => true,
        'auto-delete-tenant-database' => env('TENANCY_DATABASE_AUTO_DELETE', false),
        'auto-delete-tenant-database-user' => env('TENANCY_DATABASE_AUTO_DELETE_USER', false),

        'force-tenant-connection-of-models' => [
            App\Role::class,
            App\Permission::class,
            Spatie\Permission\Models\Role::class,
            Spatie\Permission\Models\Permission::class,
            \App\Operator::class
        ],
        'force-system-connection-of-models' => [
            App\User::class,
            \App\Account::class
        ],
    ],

    'routes' => [

        'path' => base_path('routes/tenants.php'),
        'replace-global' => false,
    ],

    'folders' => [
        'config' => [
            'enabled' => true,
            'blacklist' => ['database', 'tenancy', 'webserver'],
        ],
        'routes' => [
            'enabled' => true,
            'prefix' => null,
        ],
        'trans' => [

            'enabled' => true,
            'override-global' => true,
            'namespace' => 'tenant',
        ],
        'vendor' => [

            'enabled' => true,
        ],
        'media' => [

            'enabled' => true,
        ],
        'views' => [
            'enabled' => true,
            'namespace' => null,
            'override-global' => true,
        ]
    ]
];

```

__webserver.php config__
Default configuration of webserver.php
```php

```

---

__Error log__

```text
[2019-03-27 18:08:09] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'neotrm.operators' doesn't exist (SQL: select * from `operators` where `id` = 1 limit 1) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'neotrm.operators' doesn't exist (SQL: select * from `operators` where `id` = 1 limit 1) at /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'neotrm.operators' doesn't exist at /home/ze/projects/trm/neotrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'neotrm.operators' doesn't exist at /home/ze/projects/trm/neotrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61)
[stacktrace]
#0 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2120): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#3 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2108): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2594): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2109): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(519): Illuminate\\Database\\Query\\Builder->get(Array)
#7 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(503): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#9 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1475): Illuminate\\Database\\Eloquent\\Builder->first()
#10 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/ImplicitRouteBinding.php(37): Illuminate\\Database\\Eloquent\\Model->resolveRouteBinding('1')
#11 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(787): Illuminate\\Routing\\ImplicitRouteBinding::resolveForRoute(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Routing\\Route))
#12 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(39): Illuminate\\Routing\\Router->substituteImplicitBindings(Object(Illuminate\\Routing\\Route))
#13 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#17 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#20 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#23 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#24 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#25 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#26 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#27 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/ze/projects/trm/neotrm/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/ze/projects/trm/neotrm/vendor/barryvdh/laravel-cors/src/HandleCors.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/ze/projects/trm/neotrm/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/ze/projects/trm/neotrm/vendor/hyn/multi-tenant/src/Middleware/EagerIdentification.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Hyn\\Tenancy\\Middleware\\EagerIdentification->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/ze/projects/trm/neotrm/vendor/hyn/multi-tenant/src/Middleware/HostnameActions.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Hyn\\Tenancy\\Middleware\\HostnameActions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/ze/projects/trm/neotrm/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#60 /home/ze/projects/trm/neotrm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#61 /home/ze/projects/trm/neotrm/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#62 /home/ze/projects/trm/neotrm/server.php(21): require_once('/home/ze/projec...')
#63 {main}
"} 

```

**Comment by luceos** [comment]
You are referring to Route model binding?

**Comment by Punksolid** [comment]
@luceos yes, Route Model Binding. so I could do

```php 
    public function destroy(Operator $operator)
    {
        if ($operator->delete()){
            return response([
                "message" => "The Operator deleted succesfully."
            ]);
        }
```
instead of: 
```php
    public function destroy( $operator)
    {
        $operator = Operator::findOrFail($operator);
      $operator->delete()
```

is it possivel?

**Comment by bkintanar** [comment]
@Punksolid 	what's your route signature looks like?

**Comment by Punksolid** [comment]
@bkintanar I'm trying to make it work on my 'operator' resource
```
| Method    | URI                         | Action                                           | Middleware                                                |
+-----------+-----------------------------+--------------------------------------------------+-----------------------------------------------------------+
| GET|HEAD  | api/v1/operators            | App\Http\Controllers\OperatorsController@index   | api,auth:api,App\Http\Middleware\IdentifyTenantConnection |
| POST      | api/v1/operators            | App\Http\Controllers\OperatorsController@store   | api,auth:api,App\Http\Middleware\IdentifyTenantConnection |
| GET|HEAD  | api/v1/operators/{operator} | App\Http\Controllers\OperatorsController@show    | api,auth:api,App\Http\Middleware\IdentifyTenantConnection |
| PUT|PATCH | api/v1/operators/{operator} | App\Http\Controllers\OperatorsController@update  | api,auth:api,App\Http\Middleware\IdentifyTenantConnection |
| DELETE    | api/v1/operators/{operator} | App\Http\Controllers\OperatorsController@destroy | api,auth:api,App\Http\Middleware\IdentifyTenantConnection |
+-----------+-----------------------------+--------------------------------------------------+-----------------------------------------------------------+

```

I have this middleware that receives the tenant uuid in the header 
```php
class IdentifyTenantConnection
{
    
    public function handle($request, Closure $next)
    {

        $request->tenant_account = Account::where('uuid', $request->header('X-Tenant-id'))->first();
        $environment = app(\Hyn\Tenancy\Environment::class);
        $environment->tenant($request->tenant_account);

        return $next($request);
    }
}
```

I just personalized the Website model to work as an Account model. Its basically the same but more semantic to my app and I have some relationships attached.

**Comment by bkintanar** [comment]
@Punksolid Route Model Binding should work out of the box with this package. I'm using it in one of my projects so I know it's working. 

Are you sure you're hitting the tenant connection?

What's the output for this code:
```php
Account::where('uuid', $request->header('X-Tenant-id'))->first();
```

**Comment by Punksolid** [comment]
@bkintanar yes, its hitting that middleware because it's the only part where the tenant is set. And all others methods gives the rights registries.
I think Route Model Binding works out of the box because the subdomains are present everytime in the default configurations. But I sending them through a header. I don't know where is that set, or how to specify behavior.
 
If as I said before, if I don't use Model Binding it works as expected 
```php
    public function destroy( $operator)
    {
       $operator = Operator::findOrFail($operator);
        $operator->delete()
```

but if I use model binding gives me an SQL Error where it tries to access the table in the main system database.

I think that I will refactor all controllers for now.

I think that I need to do something in the RouteServiceProvider in order to make it work but I don't know where to start.

Thanks for your responses.

**Comment by bkintanar** [comment]
can you try to add this after the initializing `$environment`?

```php
if ($fqdn = optional($environment->hostname())->fqdn) {
    config(['database.default' => 'tenant']);
}
```

That will make it
```php
class IdentifyTenantConnection
{
    public function handle($request, Closure $next)
    {
        $request->tenant_account = Account::where('uuid', $request->header('X-Tenant-id'))->first();
        $environment = app(\Hyn\Tenancy\Environment::class);
        $environment->tenant($request->tenant_account);

        if ($fqdn = optional($environment->hostname())->fqdn) {
            config(['database.default' => 'tenant']);
        }

        return $next($request);
    }
}
```

**Comment by Punksolid** [comment]
@bkintanar didn't work, that's because `$environment->hostname()` returns null because I don't use hostnames, just the tenants, it is simplified in that way, and also setting the variable $fqdn in the if is worthless because it's not needed after. 

But, even if I put directly the  `config(['database.default' => 'tenant']);`
directly don't work. I bet the Routes Model Bindings are resolved before it touches the middlewares. But I'm not sure.

Thanks

**Comment by luceos** [comment]
Instead of using provided snippet of b8, try this:

```php
class IdentifyTenantConnection
{
    public function handle($request, Closure $next)
    {
        $request->tenant_account = Account::where('uuid', $request->header('X-Tenant-id'))->first();
        $environment = app(\Hyn\Tenancy\Environment::class);
        $environment->tenant($request->tenant_account);

        if ($request->tenant_account) {
            config(['database.default' => 'tenant']);
        }

        return $next($request);
    }
}
```

Anyway, the database connection should already be defined when the tenant is activated. Most likely your Middleware is running **after** the ModelBindings one, maybe you can influence the Kernel directly to shift this IdentifyTenantConnection way up?

**Comment by matthewmnewman** [comment]
I had a similar issue due to the middleware priority. Modify your kernel to prioritise the Tenant middleware and this should resolve the issue.

```  
 protected $middlewarePriority = [
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\Authenticate::class,
        \Illuminate\Session\Middleware\AuthenticateSession::class,
        \App\Http\Middleware\TenantSwitcherMiddleware::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
        \Illuminate\Auth\Middleware\Authorize::class,
    ];

**Comment by Punksolid** [comment]
Thank you @matthewmnewman, as far as I have looked it works!
I tried on one endpoint and it worked. I tried on an endpoint that didn't need that middleware and as far as it looks didn`t fail.
I ran all PHPUnit test and I dont see any specific error.
So it looks like the right solution. 
Interesting to know that property.
Left my code this way.
```php
    protected $middlewarePriority = [
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \Illuminate\Session\Middleware\AuthenticateSession::class,
        IdentifyTenantConnection::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
        \Illuminate\Auth\Middleware\Authorize::class,
    ];
```

Thanks
I will inform if something fails later.
